### ISSUE TITLE
The 4xAA (SSAA) setting doesn't work anymore in VR since the 4xAA (SSAA) option is removed in the table settings.

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#1005]
**Describe the bug**
The 4xAA (SSAA) setting doesn't work anymore in VR since the 4xAA (SSAA) option is removed in the table settings.

**To Reproduce**
In the previous versions(before the *ini files per table) all tables that had the 4xAA (SSAA) setting enabled in the "old table menu" which had _SSAA/post proc./AO/Screenspace reflection options per table_ :  4xAA (SSAA) worked great in VR. 
Hereby an image of the option that doesn't work anymore: https://imgur.com/5YSXP5K

Now since these options are removed, all tables shimmer massively in VR. Because the *.ini file only works for 2D settings. 
The VR settings are completely ignored by these *ini's and the 4xSSAA setting is simply not available in the "VR settings" menu. So it's impossible to enable it now. 

Where is the 4xAA (SSAA) setting for VR located? How can I enable it again? It's not in VR settings (never was) so it seems to be impossible to get this working again. I tested an old release, version 1394 and there was WAY less shimmering with that version with the exact same settings simply because 4xSSAA worked in VR with that version.

**Expected behavior**
An option to enable 4xAA (SSAA) in VR. It worked with the table settings great before in VR, now not anymore. Please bring it back.

**Versions & Settings**
 - VPX: latest 10.8 VPinballX_GL-10.8.0-1635-da14fd0-Release-win-x64
 - My ini file could be found in bug report 811: https://github.com/vpinball/vpinball/issues/811

**Additional context**
All other VR settings ALSO don't work with the *.ini. All overrides currently only work for 2D players. So the removal of the setting per table is a HUGE loss for VR users. I had all 200+ VR tables tweaked with these settings, now nothing works anymore.

I really hope that this could be fixed since it's mandatory for VR users to get the least amount of aliasing. Thank you in advance!

**Comment by vbousquet** [comment]
The settings are in the process of a massive redesign since they do not work well anymore with the new uses of VPX in 10.8+ (Direct X / OpenGL, Normal / VR, fake/real stereo with anaglyph or 3D TV,....).

I have just moved the VR part to the new (now global) system. VR settings are now just the VR one. All other settings are part of the normal video settings (like for 3D TV or anaglyph) and can be overriden there per app or per table.

Table properties are no more meant to be user settings: all user settings are moved to settings.
