### ISSUE TITLE
severe framedrop on some tables using GL 64

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#1058]
**Describe the bug**
It appears that some flashers on certain tables are causing a severe frame drop, which is noticeable even without starting a credit, in attract mode.
I have observed this problem on the following tables, though it may be present on more tables:

BK2K [https://vpuniverse.com/files/file/9054-black-knight-2000-williams-1989-w-vr-room/](https://vpuniverse.com/files/file/9054-black-knight-2000-williams-1989-w-vr-room/)
Class of 1812 [https://vpuniverse.com/files/file/8152-class-of-1812-gottlieb-1991-w-vr-room/](https://vpuniverse.com/files/file/8152-class-of-1812-gottlieb-1991-w-vr-room/)

**To Reproduce**
Open one of the mentioned tables using VPX GL 64 with the frame pacing option activated, then press F11 to view the frame rate. You will see a red indicator signifying severe frame drop. If you start playing, you will notice that it becomes more noticeable when certain lights are on.
I also encountered the same issue while playing Theatre of Magic.

**Expected behavior**
The frame rate should maintain at 120 or 60fps without any frame drop.

**Versions & Settings**
 - VPX: 1692 GL 64
 - Windows 10
 - GPU: RTX 3080
 - ini files attached for both tables

I also attempted to disable frame pacing on both tables, but still experienced a lot of frame drops making the table unplayable due to ball stuttering.

**Additional context**
[ini files.zip](https://github.com/vpinball/vpinball/files/13241763/ini.files.zip)

**Comment by pacleary** [comment]
I noticed this with VPW's Cactus Canyon as well. I normally get 155-165 FPS. But I was getting 90-110. Could be related to the caching issue.

**Comment by pacleary** [comment]
Just downloaded 1712 and the tables that were giving me FPS issues are back at 150-165 FPS.

**Comment by dacstyle** [comment]
I still have the frame Drop problem on Class of 1912 and BK2K with 1712

**Comment by pacleary** [comment]
Hmm. I have a 6600XT which is certainly underpowered compared to a 3080. I am able to run Class of 1812 at 150 to 165 FPS with anaglyph 3D settings on. Black Knight 2K is a solid 165 in anaglyph 3D. Have you tried deleting the cache and ini files?

**Comment by michroch** [comment]
Not just GL, but DX also. Got severe fps drop when playing the latest VPW Godzilla with DX64 Rev. 1726, if I go back to DX64 rev 1697, the table plays great without any drop.

Table: https://vpuniverse.com/files/file/15933-godzilla-sega-1998-vpw/

Versions & Settings:
1080 60hz
Windows Spectre 10
I7 5820K
Nvidia GTX 1660 Super 6G

**Comment by apophis79** [comment]
You guys will need to include your vpinballx.ini file if you want your comments to have any bearing. Without that there is no way for the devs to know how your system is set up.

**Comment by michroch** [comment]
Humm ! Don't know if because I went back to Rev. 1697 or put to the latest Rev. 1731, but now, everything is fine with the VPW Godzilla table in DX 64 bits.

**Comment by dacstyle** [comment]
This is my vpinballx.ini
[VPinballX1.txt](https://github.com/vpinball/vpinball/files/13315110/VPinballX1.txt)

**Comment by dacstyle** [comment]
I'm adding more information:
I have spoken with some friends about this problem, and the strange thing is that they experience the same issue, but with different tables.
For example, one friend can play perfectly on the "Class of 1812" and "BK2K" tables, but cannot play properly on "Red and Ted's Roadshow".
On the other hand, I can play perfectly on "Red and Ted's Roadshow", but I can't play well on the other two.

In all cases, we tried clearing the cache, deleting the nvram, and re-downloading the tables, always using the same versions in each of our cabinets.

It's strange.

**Comment by SuperFromND** [comment]
I've also noticed this issue on a few tables myself; the two in particular that seem to utterly murder performance are VPW's [RollerCoaster Tycoon](https://vpuniverse.com/files/file/15973-rollercoaster-tycoon-stern-2002-vpw/) and [Big Bang Bar](https://vpuniverse.com/files/file/13634-big-bang-bar-capcom-1996-vpw/), particularly with the VR rooms enabled.

I tried using the FPS display to see if I could get specific benchmarks on performance, but I play almost entirely in VR and unfortunately the graph is illegible on the preview window because of it, so I can't get hard numbers. I can definitely FEEL the performance drop though, and I know it isn't my hardware (cable, headset, GPU, etc.) that's at fault as I can run other VR games perfectly fine.

**Comment by SuperFromND** [comment]
Okay, I just spoke with some folks over on the VPinhub Discord and it turns out that the main cause of this performance hit is, of all things, _Windows Real-Time Protection._ Whenever a flasher is activated, apparently Defender scans the Visual Basic script that comes with the table (and likely any other scripts being used by VPX at that point in time), and that is the root cause of the performance drop.

Temporarily disabling Real Time Protection completely fixed the stutter issue, at the cost of some mild annoyance at having to enable/disable it every time I want to play VPX and obvious security concerns with disabling said protection.

![image](https://github.com/vpinball/vpinball/assets/22881403/eef0abe3-18b2-4969-99f9-1c15fd8f630a)

**Comment by dacstyle** [comment]
I don't have that option enabled, and it only occurs on certain tables, That is not my case.

**Comment by vbousquet** [comment]
Solved in latest
