### ISSUE TITLE
Highlights blow out since adding tone mapping

### ISSUE THREAD

**Issue by a-bord** [vpinball/vpinball#1062]
Since the addition of tone mapping the highlights blow out pretty badly.

If I look at a screenshot from a pre-tonemapping build I get this:

![image](https://github.com/vpinball/vpinball/assets/90645800/98a4d7a6-a645-4d5d-98d1-ccc163f917bb)

But after tone mapping was added I get this (both tone mapping options):

![image](https://github.com/vpinball/vpinball/assets/90645800/84442151-6e49-48d0-898d-b98abd222a1f)

I see this on other games as well (look at the bumper caps on Haunted House). IMO this is not a desirable change.

**Comment by a-bord** [comment]
I should say, in general I like what the tone mapping can do, but I think it is pushing highlights much too far currently.

**Comment by vbousquet** [comment]
In latest builds, you should be able to select the tonemapper of your choice. Reinhart is the one available before 1038 and should give the exact same results (since ti is the exact same math, untouched).

I'm updating the part for transmitted light (light from below) which has bugs (it does not give the same result in dynamic mode like VR/headtracking than in static mode like desktop). This may be the cause of this added burst

**Comment by vbousquet** [comment]
Looking again at your shot, it indeed looks like a tonemapper or emission scale effect (burst is everywhere)

**Comment by vbousquet** [comment]
Do you have a table file to test this to understand what is happening here ?

**Comment by vbousquet** [comment]
I made a few more tests with Haunted House.

This with 10.8 Beta 5:
<img width="1024" alt="Beta 5" src="https://github.com/vpinball/vpinball/assets/2796036/fc0605b1-736c-46be-b044-712b20a6ba3a">

This is with latest 1705, using the default Reinhart tonemapper:
<img width="1024" alt="Alpha 1705 Reinhart" src="https://github.com/vpinball/vpinball/assets/2796036/48f97cb3-eb4a-4cb0-a160-a4e0d8a1e426">

And this is with latest 1705, using the new Tony McMapFace tonemapper:
<img width="1024" alt="Alpha 1705 Tony McMapFace" src="https://github.com/vpinball/vpinball/assets/2796036/860eb590-25a8-4a2c-a189-a774f04916f1">

It looks to me that there was no change between beta 5 and latest 1705 build (as expected). It also seems to me that the new tonemapper does not blow out, but in fact less (which is also what I expected since it is supposed to be more balanced and desaturate earlier and smoother).

I'm not sure what is the problem you're experiencing with Rock Makers but I don't think it's linked to the tonemapper. There is nothing I can do without more informations here

**Comment by pacleary** [comment]
VPW's Cactus Canyon is also giving me some weird lighting effects. 1705 on the right.
![cc-example](https://github.com/vpinball/vpinball/assets/128317770/80db1191-3fc9-4eeb-a9e6-253fc61c3e0c)

**Comment by dacstyle** [comment]
Lights looks so bad on VPW's whirlwind

**Comment by toxieainc** [comment]
> In latest builds, you should be able to select the tonemapper of your choice. Reinhart is the one available before 1038 and should give the exact same results (since ti is the exact same math, untouched).

You did change the order of operations though (AO and Bloom).

**Comment by vbousquet** [comment]
> > In latest builds, you should be able to select the tonemapper of your choice. Reinhart is the one available before 1038 and should give the exact same results (since ti is the exact same math, untouched).
> 
> You did change the order of operations though (AO and Bloom).

Yes, but I don't think this was the issue here (I did quite some testing to see how this swaps impacts the visual and it is very very limited).

I also made a bunch of 'optimization' commits since as things build up, I'd like VPX to run full speed, with frame pacing, with stereo anaglyph, headtracking at 4K on my loosy 10+ year old setup :) ... Namely, I added:
- move alpha test out of the way since it breaks early depth testing and it is not needed most of the time,
- disabled alpha blending when not needed (difficult to tell since authors use a workaround of alpha=0.999 for other purposes),
- add scissor for blurring operations and reflection rendering,
- try to move to opaque pass all opaque parts (to benefit more from early depth test).

Some of these optimizations were too agressive, so I have just reverted some:
- [fix the lighting from below errors (like this one)](https://github.com/vpinball/vpinball/commit/6d950e8ec8e36b179f63a222b43c8f5410933586) 
- [fix some render sorting problem linked to the opaque evaluation (some tables expect opaque parts to be masked out by transparent ones)](https://github.com/vpinball/vpinball/commit/4feea628a090b34246c2ba7ad9462c7140a52964)

@a-bord Could you confirm that things are solved now (using the latest build, I just pushed)

**Comment by dacstyle** [comment]
I checked whirlwind with the latest and some lights are now working, for example the compass.
But some lights from below still not working like the skill shot, NW, NE.

The new opaque effect when all the lights are off is SUPERB. I tested TAF and was shocked on how real it looks. Congratulations and thank you.

**Comment by vbousquet** [comment]
Whirldwind should be good in latest now

**Comment by pacleary** [comment]
Lighting looks good to me in the tables I tested in 1712.

**Comment by dacstyle** [comment]
> Whirldwind

Yes works perfectly  now. Thank you.

**Comment by pas-de-2** [comment]
I am seeing this weird blown out lighting when playing in VR with two tables in the latest beta release. VPW's [Bride of Pinbot](https://vpuniverse.com/files/file/12029-the-machine-bride-of-pinbot-williams-1991-vpw-mod/), and DGrimmReaper's [VR conversion of JP's Pokemon Pinball](
https://www.vpforums.org/index.php?app=downloads&showfile=17605). The light is so blown out it turns to black and starts distorting the screen. (Sorry for low res crops, not sure how to SS properly in VR)

![bleed1bride](https://github.com/vpinball/vpinball/assets/116680301/7841d8c2-0702-4a7f-b0bc-4054f260deca) 
![bleed2pokemon](https://github.com/vpinball/vpinball/assets/116680301/4377f981-a9cf-4e3e-a137-3c398904b63f)
