### ISSUE TITLE
Flat ball when enabling cabinet anti-stretch in portrait mode

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1171]
**Describe the bug**

Just upgraded to 10.8 beta 6 and put my playfield in portrait mode

When I choose `cabinet anti-stretch` the ball looks like this

![image](https://github.com/vpinball/vpinball/assets/161305/70017352-0c43-481f-9d0e-468f7f83ecce)

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

https://vpuniverse.com/files/file/16321-spongebobs-bikini-bottom-pinball-vpw/

![image](https://github.com/vpinball/vpinball/assets/161305/84efbafc-46ad-4893-8b6d-ace20735d321)

**Comment by francisdb** [comment]
I fear I still have issues here on the latest build. Now it seems to overcompensate when requesting round ball. Or is this an illusion?

The simpsons VPW with default

![image](https://github.com/vpinball/vpinball/assets/161305/4bef3027-73ec-49e8-971d-a706fb28582a)

The simpsons VPW with `Force round ball (compensate perspective stretch)`

![image](https://github.com/vpinball/vpinball/assets/161305/7134f5f3-062c-4a81-aa4b-74b616f8c567)

**Comment by vbousquet** [comment]
The new implementation ensure that the ball is a circle. But this introduces the possibility that it will enlarge on the y axis which may be unwanted (it is somewhat difficult to do something meaningful on this feature since the ball will never be mathematically and visually correct).

One way to improve the thing would be to only allow shrinking on y/z axis and not enlarging. I will give it a go
