### ISSUE TITLE
POV Files not Saving

### ISSUE THREAD

**Issue by fink1982** [vpinball/vpinball#1178]
When I hit the button to safe the POV in the POV alteration screen after amending any table it doesn't save, I tried deleting the POV file in the table folder and it makes no difference, I believe it may be an issue with the new global settings overriding the POV file, also amending any of my existing JP tables POV in 10.6 beta 6 stops them from working when trying to reopen the table. As if something has been corrupted, VP locks up and crashes. 

JP's Deadpool is the table I've had the most issues with although I can't get any POV settings to save.  

**Additional context**

**Comment by studlygoorite** [comment]
Maybe this will help you......I just spent all day re-doing POVs and Deadpool was one of them. Can't remember specifically if it was that table but I had issues saving with some also. I found that when in the POV screen and make changes that you need to hit start to save the POV  while in that screen. I was changing the POV and then going to the next screen to check day/night and tonemappers changing them and hitting start and this caused something to not save. No issues since I have started hitting the start button on the POV Screen when done there and then again on the Tonemapper/day/night Screen when done there. By the way, be sure to check the "filmic" tonemapper on tables that are a little washed out, it's awesome.

**Comment by fink1982** [comment]
Hi, Thank you for the reply, I redownloaded the tables that have been corrupted and tried but no change, are you using the GL or DIrect X version of Visual Pinball, my issue is while using the GL version, should have put this in my original post, Thank you for the heads up regarding Filmic, I'll give it a go.

**Comment by studlygoorite** [comment]
Ah, using Direct X here.

**Comment by mark4par** [comment]
My POVs don't save in adjust camera while the table is playing either. I have to close the table and change them manually.

**Comment by mbp2728** [comment]
Hello, when you say POV, are you talking about files with extension INI or POV? In version 10.8.6, there´s no way to save POV extension files anymore and I´m dissapointed because my entire system (more than 400 tables) are based on .POV files.

**Comment by francisdb** [comment]
As far as I know pov file values should still be picked up but new saves are indeed in the ini.

**Comment by mark4par** [comment]
when you restart the table the view is back to default and nothing saves. I have to manually change it in the editor. It used to work in adjust camera with the live table going. You quit VPX and it just closes instead of ask you if you want to save changes and views are back to default.

**Comment by francisdb** [comment]
In the pov edit mode (F12) you have to press start (1) to save the pov to the ini file.
