### ISSUE TITLE
Flipper / Solenoid problem

### ISSUE THREAD

**Issue by retro27** [vpinball/vpinball#1190]
**Describe the bug**
When using the flippers on Stones_10_RTM_1.5_Final, its causing the Solenoids to activate that set  to activate on pressing the Manga buttons
This started happening from 10.8 .0 Build 1444
https://github.com/vpinball/vpinball/actions/runs/6200761548

**To Reproduce**
1. Download latest build of VPX10.8.0
2. Load Stones_10_RTM_1.5_Final found at https://vpuniverse.com/files/file/3573-stones_10_rtm_15_finalrar/
3. Start Game, when activating the flippers, the Solenoid are triggering for LUD and RUD. The Solenoid should only activate on the Magna Buttons

**Expected behavior**
When pressing the flippers, the Solenoids should not trigger, They should only trigger when pressing the Magna Buttons

**Video**

https://github.com/vpinball/vpinball/assets/16049569/98fb60e8-840e-4d91-a90b-9ee1e61b42b3
This video shows the solenoids activating when pressing the flippers,  and show what happens when the manga buttons are pressed.

**Versions & Settings**
 - 10.8.0 Latest Build
 - Windows version 11 Pro
 - Nvidia  RTX 3070

**Comment by wiesshund** [comment]
Not a bug, ask the author to update the table per staged flippers

It has to do with how that table was wired up and what they used in the controller

you can add these lines to the top of the script below the first const

`const cSingleLFlip = 0
const cSingleRFlip = 0`

**Comment by retro27** [comment]
Thank you wiesshund, Problem fixed.

**Comment by wiesshund** [comment]
> Thank you wiesshund, Problem fixed.

If you are wondering why it changed
VPX did a poor job previously of handling staged flipper equipped machines in an intuitive fashion that simply worked
plus VPX itself had no means for the player to assign keys and buttons to them, which results in people having to use either a helper app or switch their controller encoding to keyboard.

So i reworked all the machine translations, and then Toxie added native support in VPX's keymapper.
So now a player can just go in the keymapper and set staged flips to what ever keyboard keys in vpmkeys.vbs
and they also assign it a button number if their controller emulates joystick buttons, and the result is press button number, VPX magically sends the appropriate keyboard key to vpinmame.
No joy2key etc required.
And by default vpmkeys.vbs just says staged flip = flipper key

And all a table author has to do is simply use the correct solenoid callback
and give it the staged flip's routines.

So why did that change your table?
Because of how the ROM is wired.
That table has the circuitry to do staged flips, but it is not used, it is all tied to the single set of flipper buttons
but it does not actually do anything, it isnt connected physically.
Vpinmame does not know that there is no physical connection, so when you hit the flipper key, it's engaging what would be the upper flipper circuits, which got repurposed in this specific machine to do something else. 

This happens a lot, they just program the ROM to use things in a non standard way and then dont need to design a special controller, they can steal lamp inputs and reprogram them to fiire solenoids etc.

Haunted Hotel, LTD stole so many inputs for non standard use that they only had 1 switch circuit left for coins
so there is only 1 coin switch

Anyways, those 2 lines
const cSingleLFlip = 0
const cSingleRFlip = 0
Prevent the single button from firing the non present upper flips
