### ISSUE TITLE
Lights bloom and far too bright to use on some tables -- DX and GL

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1228]
**Describe the bug**
Some tables the lights are WAY too bright using DirectX version.
two examples...Goonies & Pirate of the Caribbean. Goonies is so bright on most LUT options it very difficult to see through them.

**To Reproduce**
load table

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
goonies... https://vpuniverse.com/files/file/7819-the-goonies-never-say-die-pinball-vpw/
pirates... https://vpuniverse.com/files/file/11599-pirates-of-the-caribbean-mod-mroche-10/

**Expected behavior**
non-blooming lights

**Screenshots**
![20231202_092933](https://github.com/vpinball/vpinball/assets/1626802/0054781d-03c4-4b3d-a96f-4e3ad627502c)
![20231202_092942](https://github.com/vpinball/vpinball/assets/1626802/b560e6e1-fb0e-42d0-aa5c-8304156f127a)
![20231202_093123](https://github.com/vpinball/vpinball/assets/1626802/ae3968f2-1065-4a0e-af21-ca7f9397b9ec)
![20231202_093138](https://github.com/vpinball/vpinball/assets/1626802/a0499ed7-7d48-4b66-8821-92d1bf7b6e36)

**Versions & Settings**
 - VPX 10.8.0 Beta rev 1807 39824d6
 - Windows 11 all patches
 - NVidia RTX2060
 - INI attached as ZIP

 - Log attached as ZIP

[VPinballX_INI.zip](https://github.com/vpinball/vpinball/files/13536808/VPinballX_INI.zip)
[vpinball_LOG.zip](https://github.com/vpinball/vpinball/files/13536810/vpinball_LOG.zip)

**Comment by tweety231323** [comment]
Ball is rolling between two incandescant lights:
![2023-12-02 19_55_44-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/992a7085-5aff-4d76-9f74-6dde47c6f800)
![2023-12-02 19_57_02-Visual Pinball -  !Sittin' Pretty (Gottlieb 1958) (MaX, Robair, Furio)_build28](https://github.com/vpinball/vpinball/assets/98708681/22d73002-0c30-4ddc-a607-9ab204df533d)

**Comment by Smilelikejoker** [comment]
Hey Ltek,

I'm trying to reproduce on the Goonies table, but not having any luck.  Mine runs fine.  I'm running 10.8.0 DX (64bit & 32bit) rev 1814.

Can you upload your VPinballX.ini from your user/app data/roaming/VPinballX ?  That is the one that shows your video settings and such.  We have something different other than the revision.

**Comment by Ltek** [comment]
@Smilelikejoker thanks for the help. INI attached (sorry I didn't realize 10.8 was still using profile folders - I hope this changes since its not good for backup/recovery)
[VPinballX.zip](https://github.com/vpinball/vpinball/files/13537639/VPinballX.zip)

**Comment by Smilelikejoker** [comment]
Alrighty....  Here is what I've found.
Table - PotC https://vpuniverse.com/files/file/11599-pirates-of-the-caribbean-mod-mroche-10/
VPX 10.8.0 DX 64bit rev 1814
@Ltek 
I can reproduce the super bright bulb issue - AND - I can fix it with a simple change in the video settings.

This picture shows the setting I changed.  It is underlined in red:
 ![settings](https://github.com/vpinball/vpinball/assets/102932021/781cb85c-e820-4dc4-9bb1-fd80510e1b74)
 
 If you pick the Max Reflection Mode that is 'Dynamic' or 'Static & Unsynced Dynamic' , you will have the following issue:
 ![Dynamic](https://github.com/vpinball/vpinball/assets/102932021/d8840d05-0d82-4d07-a2a9-c8ed263d224c)
 
 To fix it, pick any of the other modes.  Here is your result:
 ![Static](https://github.com/vpinball/vpinball/assets/102932021/63197093-191b-4959-a1ed-59569e1cd3a3)
 
 It looks like the issue is related to dynamic reflections of some sort.  Hope this helps ya @vbousquet

**Comment by tweety231323** [comment]
Another example table:
[https://www.vpforums.org/index.php?app=downloads&showfile=16156]

Screenshot in VR:
![2024-02-01 20_17_12-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/e8a1a742-f4be-4857-b1d2-f948cf8a038b)

Changing "Max.Reflection Mode" to "Static & Balls" makes no difference in VR.

**Comment by Joey-2001** [comment]
Try this:
![grafik](https://github.com/vpinball/vpinball/assets/35002625/225f8594-1ce0-44f1-a7cc-3c075050613f)
