### ISSUE TITLE
[Feature Request] store VPinballx.INI in VisualPinball root, not %AppData%\roaming\VPinballX

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1231]
Please stop using profile folders (%AppData%\roaming\VPinballX).

The use of profile folders, and reg keys, is not needed by most apps and goes against current Windows app best practices for Backup/Recovery and app hygiene when data is not required to be secured by the OS.

Given that all other config files for all Vpin type apps are in the local folders, VPX's should also. Then we can simply backup one root folder to capture all needed data/settings/files for all vpin apps and associated utilities, etc. 

thank you

**Comment by jpsalas59** [comment]
I agree with Ltek.

**Comment by jsm174** [comment]
Standalone adds a `PrefPath` command line option that does this. Batocera uses this for example, to modify the path to `/userdata/systems/config/vpinball`. 

Maybe this could work and be backported into master?

From a developer side, having a "default" path other than the binary is actually helpful, as I may be working on several copies of the code. When building, the build directory is either non-existent or wiped out, and I'd have to keep copy the file. However, that said, I could always configure the command line settings with the `PrefPath`.

**Comment by jsm174** [comment]
> Or just a browse to directory in the options... in other words, select the directory where you want to keep your default in the settings. This seems like a pretty common solution in a lot of programs.

The one thing to consider with a pref path that is configured via a GUI is, at the end the of the day, something needs to seed that specific value.

ie if all the settings are saved in the ini, how do you know where to load the ini from? :)

**Comment by Drybonz** [comment]
Wouldn't it just save the location somewhere else?  I'm just an average Joe, but how does it usually work in a program where you can change file locations, etc?

**Comment by jsm174** [comment]
right now, the "entire" configuration for vpx has been moved from the registry into an ini file.

On windows: %AppData%\roaming\VPinballX\VPinballX.ini
On everything else: $HOME/.vpinball/VPinballX.ini

If `VPinballX.ini` contained a setting called `PrefPath` how could you even load that value in the first place?

On windows, sure you could write this to the registry, but I thought we were finally moving away from the registry since it's not cross platform.

That's why I was thinking a command line option seems like a reasonable cross platform solution?

**Comment by toxieainc** [comment]
I will check how to make this an UI based option.

**Comment by toxieainc** [comment]
I put some more thoughts into this, how to solve the chicken/egg problem:
By default VPX creates the 'first' ini in the AppData folder.
If switching this via the new UI option (in the INI/Editor/UI preferences), that one gets moved to the .exe folder.
On loading VPX, it checks if there is an .ini in the .exe folder, if yes, it takes that one, otherwise the AppData one.

If the UI option is switched again, the .exe folder ini gets moved to AppData again.

@vbousquet Is this okay with you? If yes, i would merge to 10.8.0.

**Comment by jsm174** [comment]
The pref path is more than just the ini, isn't it the user directory, potential music folder, etc. I'm sure can make this work in standalone, but it does seem confusing.. especially in iOS / Mac where app bundles can't have data written inside it.

**Comment by toxieainc** [comment]
Pref path is only these two files and the cache from my understanding.
The other files are only optionally stored there, if these cannot be found.

**Comment by jsm174** [comment]
yes, you're right. Now I remember. I leveraged pref path because of iOS and Android not being able to write anything in the directory where the executable is, and needed something for user and music.

**Comment by vbousquet** [comment]
On my side, I do not have great concerns nor wills against any options. What you will choose will be ok whatever.

I moved everything to the AppData folder since this is what Microsoft requires for 'good behaving' applications. I think the 'old' way of putting everything inside the application folder has been deprecated for years, and this likely will need some user right overrides at some point to behave correctly (either puts application outside of the shared application folder or give privileged rights to the app to write in it). So, I was thinking that moving toward what the platform requests should be done in order to avoid problems and to behave like other apps, beside this should also allow better portability.

So I guess, if we really want this to be an user option, a nice way would be to have everything (ini, cache, user, music,...) that needs write access to be placed by default to where the platforms requests it, but also allow to move them like @toxieainc proposed.

**Comment by Ltek** [comment]
@vbousquet @toxieainc IMO Toxie's solution is a good option that provides choice and ease-of-administration for the user.

In the future I'd love to see vPin related/interacting apps (VPX, Popper, B2Sserver, etc) store ALL config files in a single folder  (front-ends, volume controls, B2Sserver, DMD, etc and maybe even table INIs). This follows UNIX/Linux app convention with separate bin, config, etc. ... thus ease of Backup/Recovery, and consistency. There are so many thing that overlap/step-on across apps its a real challenge knowing 'what' files store configs and what folders they are in. 

anyway, for now, root of VisualPinball is a nice option! thank you.

**Comment by toxieainc** [comment]
Backported to 10.8.0, so closing..
