### ISSUE TITLE
Degraded / blurry image in stereo 3D modes

### ISSUE THREAD

**Issue by jueank** [vpinball/vpinball#1241]
Using 10.8.0 beta 7, 64bit, GL version.

This issue is closely related to this issue: https://github.com/vpinball/vpinball/issues/1230, but might have a separate root cause or needs to be fixed separately.

When using stereo 3D modes (interlaced, L/R, top/bottom), the X scaling has to be set to ~50% currently, because of the linked issue above. Table will be rendered same size as with X scaling at ~100% and stereo 3D modes 'disabled'.

Observation:
The rendered table in stereo 3D modes has a degraded or a 'blurry' image quality compared to not using stereo 3D modes. This can easily be seen when starting the table in stereo 3D mode and then switching stereo 3D mode OFF (F10). Exact difference can be seen when comparing to the table being started (that is important!) in 'standard' 3D (3D Stereo Output set to 'Disabled') (in that case, X scaling has to be set to 100% in order to have the table rendered at the same size).
The following link shows the difference between the 2 cases quite well: https://imgsli.com/MjI0MDU3

Expectation:
It might sound obvious at first that the image is more 'blurry' when X scaling is set to 50%, but since the table is rendered in both cases at the same 'final' size on screen, I would expect that the resolution/quality of the rendered image is the same.

I will also attach the images of the table in interlaced 3D mode. The difference can be seen there as well (but only in a good way when using a 3D TV).

Btw. - weird enough - the degraded image looks quite good/better (at least in some areas) than the 'better' rendering (both in stereo 3D), because the stair stepping is not so strong / the image parts for left + right eye are more similar because of the blurring. This might be the start of an 'intelligent' enhancement for stereo 3D in order to reduce stair stepping... Needs to be properly implemented for sure...

![1 - X scaling reduced by 2, stereo 3D mode switched OFF](https://github.com/vpinball/vpinball/assets/42673804/7dd9ec2c-873d-4015-8729-738aedc99152)
1 - X scaling at ~50%, Table started in interlaced 3D mode, then stereo 3D mode switched OFF (F10)

![2 - X scaling original, table started with standard 3D mode](https://github.com/vpinball/vpinball/assets/42673804/1d1fc300-e9fe-4687-aea7-e9c90bd99140)
2 - X scaling ~100%, table started with 3D Stereo Output 'Disabled' (no stereo D, no fake stereo 3D, no anaglyph 3D)

![3 - X scaling reduced by 2, stereo 3D mode ON](https://github.com/vpinball/vpinball/assets/42673804/6c81ae4a-9248-4599-9923-810a25912896)
3 - Same as '1' (X scaling at ~50%, Table started in interlaced 3D mode), stereo 3D mode NOT switched off (still on)

![4 - X scaling original, stereo 3D mode ON (can be done when switching to stereo 3D mode in Live Editor (F11))](https://github.com/vpinball/vpinball/assets/42673804/0ad45544-bf73-42b7-a242-5d02f03b2c21)
4 - X scaling at 100%, Table started in anaglyphic 3D mode, then switched to interlaced 3D in Live Editor (circumvents the X scaling issue). This is how the rendered image of the table is supposed to look like correctly (imho)

**Comment by gjupp** [comment]
Interesting observation. Can you please label the images underneath each so we can tell which is which.

I tried both of those 3D images on my 1080p LG 3D screen at full screen and noticed that they both appear to have inverted 3D, I'm not sure if my 3D filter is different to yours or if its because of the monitor rotation direction, my LG logo is at the left side of my screen in portrait orientation, what is yours?

Does the depth look fine to you? Have you got yours set to interlaced or flipped interlaced?

**Comment by jueank** [comment]
I added descriptions to the pictures. Also added some text to clarify what I mean with 'standard 3D'. This is none of the stereo D options picked (no anaglyph, no interlaced, no fake stereo 3D).
I use interlaced 3D (not flipped interlaced). The lower side of the TV (LG label) is on the left side as well in my setup.
The depth is generally ok. Because of the linked issue (#1230), the eye distance has to be reduced from cm to 31.5cm

I don't think that the explanation with 'halving of the screen resolution' is sufficient. In all above cases, the table is rendered taking the same size on screen - irrespective of X scaling being 50% or 100% or whether stereo 3D is on or off. It's the internal treatment in VPX before generating the final image. There should be no reason why in the first case, the image is degraded and blurry compared to the other cases.

**Comment by gjupp** [comment]
Ah.... with those labels it's a lot clearer what you mean thankyou.

I do recall that Vincent has mentioned that if you are using GL and have a 3D mode selected in graphics settings, then using F10 to "disable" 3D from within the game does not really turn it off in terms of the processing hit. What it does is simply shows you the view from a single eye render of the stereo pair (not sure if its the left or right eye render). This is likely why your first image (1) still looks to be lower res. As an aside, f you want to get the framerate higher in 2D flat mode you need to disable 3D in graphics settings.

It is very odd though that the issue is corrected by first starting in anaglyph mode and then switching to interlaced. Guessing it is just dropping every other line of the left and right anaglyph images and then interlacing them together as full colour interlaced. Probably a good clue there for Vincent to discover the issue.

It may be that it is actually working as intended (aside from the need to reduce X to 50%, as whilst image 4 is sharper, image 3 does provide better antialiasing at the expense of being a softer image overall.

Interesting regarding the two different pairs of glasses that you have. I'm using a pair of RealD 3D glasses from local cinema here. I was able to see your images in correct 3D depth by flipping them upside down.

**Comment by jueank** [comment]
Thank you for sharing your thoughts.

If you start a table with '3D Stereo Output' set to 'disable', you cannot switch to any of the Stereo 3D options later on in the Live Editor (F7). Only if the table is started in one of the Stereo 3D modes (Stereo 3D rendering can not be started on the fly while the table is 'running'). That is in fact the only reason why I wrote that you have to start the table in 'Red/cyan'![image](https://github.com/vpinball/vpinball/assets/42673804/699a28fa-de12-465d-a864-ee200c5b8291)
If you pick 'interlaced' already before starting the table, you get that 'horizontal scale by 2' issue (#1230). Therefore you have to do that extra step in-between.

I understand what is happening behind the scenes when switching Stereo 3D OFF (F10), that is: still staying in the Stereo 3D rendering mode, but showing the image from a single perspective (left eye) only.

However, I still don't think that it is working as intended. I checked again, made another set of screenshots, and they prove my point. Let me explain:

I started the NBA table they same way as described above: Stereo 3D mode: Red/cyan, then switched in Live Editor to interlaced 3D. Changed the X scaling to 100%. Result is perfect Stereo 3D rendering with no blurring.
Then is switched Stereo 3D rendering OFF (F10). and voilà - the 'standard 3D' rendering (non stereo) from the perspective of the left eye also shows a perfect picture without blurring; identical to picture nr. 2 from above when I started the table with Stereo 3D mode set to 'disable' from the beginning.
That means there is no inherent reason why Stereo 3D rendering should produce a worse (or blurred or degraded) image compared to the non Stereo 3D modes. You can make it work by following the above procedure.


It all boils down to #1230 with the horizontally stretched image and the need to compensate by setting X scaling to ~50% only leading to subsequent issues. (that would be my bet)

**Comment by PG248** [comment]
@jueank great finding! Until the bug is fixed would it be a workaround to start all tables in anaglyph 3D and immediately switch to Interlaced 3D via a script?

**Comment by jueank** [comment]
@PG248 I would not know how to do that automatically. I hope the issue gets fixed in the next beta.

**Comment by vbousquet** [comment]
Fix in latest from master
