### ISSUE TITLE
Physics "Hit Event" detection does not work consistently

### ISSUE THREAD

**Issue by rothbauerw** [vpinball/vpinball#1266]
While testing physics dampeners, it's been found that the VP physics hit detection is very inconsistent. It does not always register a "hit" event when you would expect it to. This can have great impact on the dampener script, sound events, switch events and more.

The issues appears to be more severe on objects with low elasticity.

This is not believed to be a new issue, just one we have just become aware of. This has been tested on 10.8 beta 7 as well at 10.7.3 and the behavior is the same on both version of VPX.

To reproduce, you can use the following test file:

https://www.dropbox.com/scl/fi/pedtunyxfh8ggggwp0w8w/Example_Table_VPW_1.5.12_Dampener.vpx?rlkey=iot6tihvoyzhdqm4dtfq033v6&dl=0
Link to Example Table DMD: https://www.dropbox.com/scl/fi/sc3zaxbehahkwx8ibdiqj/VPWExampleTableDMD.zip?rlkey=41qlhm2sj2n4bh4fkbxtfyths&dl=0

- Load the table and open the debugger window
- Press '1' to release the ball, then press the left flipper key to test drop the ball on to the test object
- If the hit is detected, several debug statements will appear in the debugger.
- Repeated tests will show that hit events are consistently not registered (you should also notice a significant difference in the behavior of the ball)

It would be expected that anytime the ball and object collide, a hit event would be registered.

**Comment by iaakki** [comment]
With slight modifications to VPX, it seems to happen every time after initial hit.

Changes:
- I set default scatter to 0 and object scatter to 0 too. 
- Removed those plunger lane side walls, as though maybe they interfere somehow.
- In addition added these into leftflip key, so that the initial roll should not change:
		ETBall1.angmomx = 0
		ETBall1.angmomy = 0
		ETBall1.angmomz = 0
		ETBall1.velx = 0
		ETBall1.vely = 0
		ETBall1.velz = 0

https://drive.google.com/file/d/1UaIEE9V4gLUZw8Trmr2jd2nWj6Ot0KrL/view?usp=sharing

**Comment by vbousquet** [comment]
The behavior you described was the intended behavior: VPX filters out events to avoid keeping sending events of a rest position (ball resting on a wall is constently 'hitting' it). It used to be implemented by discarding events happening at (roughly) the same location. I have changed this to also take in account the time elapsed between events. If events happens at the roughly same place in a very short time lapse (equal or less of 2 physics iteration), they will be considered as rest events and therefore discarded, otherwise they will be delivered.

I guess, this may need some validating and testing since this change a behavior that has been here for a long time. (There was also a little bug in the physics testing code that I have solved and may affect your experiments).
