### ISSUE TITLE
Max Texture Dimensions - Auto Value

### ISSUE THREAD

**Issue by alaw-lufc** [vpinball/vpinball#1404]
In non VR is there any point in having max texture dimensions set higher than the screen resolution for VP?

Based on the best info i could find ( [https://www.vpforums.org/index.php?showtopic=50520&p=511922] ) my assumption is no. If that's the case, for desktop / cab users could the max texture dimensions automatically select a suitable default value (equal to screen res) whenever the Display/screen selection is changed in video prefs to help with performance?  (with the option for the user to manually increase or decrease it later if they want)

Or maybe VPX already does this internally at runtime?

**Comment by toxieainc** [comment]
The only real benefit would be coming from the fact that this is using less memory then. Performance wise it would only make a real difference if not all textures fit into GFX memory otherwise.
Cause otherwise the GFX board will do some filtering via mipmaps anyway, and this always (roughly) uses the same amount of data and access pattern per pixel.

As for the estimate itself: Its not that simple unfortunately. In an ideal scenario your assumption is right. But that ideal scenario assumes that the texture is displayed 1:1 on screen, no perspective/distortion, no translation, etc.
Everything else would need to use some kind of pessimistic estimate, a simple one being to use 2x2 the screen resolution (so for 1920x1080 that would be 3840x2160) based very very handwavy on https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem.
In practice it even very much depends on the table setup and the used POV and you may get away with smaller resolutions without quality loss.

If you're okay with some quality loss though in general for some tables, i guess just picking a maximum texture resolution in the video settings that is a bit higher than max(xresolution,yresolution) should be fine in general.

**Comment by alaw-lufc** [comment]
Thanks for the explanation. Looks like an auto value isn't really possible without making assumptions then.
I don't hav any funky pov's set up so I'll give 4096 a go with 4k and see how i get on.
