### ISSUE TITLE
10.8.1: Overdone reflections on non-pinballs balls

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1460]
**Describe the bug**

10.8.1 branch as of today

https://vpuniverse.com/files/file/15354-cue-ball-wizard-gottlieb-1992-mikcab_mod/

These reflections probably look ok on the pinball ball but should be reduced for non-chrome balls.

![image](https://github.com/vpinball/vpinball/assets/161305/8172d208-8e8e-4588-b0a5-4ba97db19939)

These balls used to look like this

![image](https://github.com/vpinball/vpinball/assets/161305/38181fd3-68b9-4ca5-ac48-26101e5c3524)

**To Reproduce**
1. Load the table

**Comment by superblobster** [comment]
The bottom ball looks really weird. Mine doesn't look like that.
However this seems like another table-specific bug.

![Screenshot 2024-02-15 232250](https://github.com/vpinball/vpinball/assets/60817163/6cd69468-5db0-481d-a97b-6da00a5f6fa3)

**Comment by francisdb** [comment]
> The bottom ball looks really weird. Mine doesn't look like that. However this seems like another table-specific bug.

Even on your screenshot the balls look like they are made from glass.

**Comment by vbousquet** [comment]
The problem here is that the reflection are too strong. If you adjust in `CreateBlackBall` and `CreateWhiteBall` with something like:
```
  BBall.BulbIntensityScale = 0.1
  BBall.PlayfieldReflectionScale = 0.1
```
This lowers them and gives a nice result.

This is not fully backward compatible (the table rely on the fact that the old reflection were not that much visible, since they were limited to very low angles) but I think that the new ball shading is really better, indeed needing some table update (only the ones using non mettalic ball which is somewhat seldom).

I will close as I don't see any solution that would at the same time keep the new and better balls, while managing these ceramic/plastic balls.
