### ISSUE TITLE
VR: B2S not shown

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1476]
**Describe the bug**
B2S is not shown over backglass primitive. It stays the selected image.

**To Reproduce**
table Pinball Lizard
[https://www.vpforums.org/index.php?app=downloads&showfile=18251](url)
Start table in VR: backglass is image, not B2S.

Load another table with the same backglass primitive (e.g. Coney Island [https://vpuniverse.com/files/file/17443-old-coney-island-game-plan-1979-jp-v402-ext2k-vrroom/](url)).
Select the VR_Backbox_Backglass image. Copy / paste it to Lizard. (Side note: table is not marked as dirty.)
![2024-02-21 10_44_32-](https://github.com/vpinball/vpinball/assets/98708681/995f28a4-2ac3-443f-a9f9-b40e794e63a7)

Press play. B2S is shown over backglass.
![2024-02-21 10_38_32-](https://github.com/vpinball/vpinball/assets/98708681/97f97648-4207-47e8-b9bd-ce75a1d5be4a)

Save the table. Press play. B2S is no longer shown over backglass.
![2024-02-21 10_38_03-](https://github.com/vpinball/vpinball/assets/98708681/bc857110-ecb3-4f34-8d54-e81948e4b9ef)

**Versions & Settings**
 - VPX: 10.8.0 GL 64bit. Tested in rev 1874 and 1890
 - Windows version 11
 
[VPinballX.ini.txt](https://github.com/vpinball/vpinball/files/14357698/VPinballX.ini.txt)
[vpinball.log](https://github.com/vpinball/vpinball/files/14357699/vpinball.log)

**Comment by Joey-2001** [comment]
It's not a bug at VPX. It's a bad conversion to VR. 
The image of the backglass must be named backglassimage. So rename the image and it works.
Otherwise there are man other things, that doesn't look correct in VR.
The alphanumeric dispay is seeable in the backglass and next to the backglass. It has to be in a collection.
Then it was invisble in VR.
The Plunger cut through the housing. The plunger is much to hard. It's 5. I reduce it to 0,25.
The artwork of the cabinet is too dark and bad. The spotlight must be increased for cabinet and backbox.
