### ISSUE TITLE
Weird DMD in VPX 10.8 Release Candidate. Can I turn it off?

### ISSUE THREAD

**Issue by PeterTucker** [vpinball/vpinball#1483]
**Describe the bug**
There looks to be an issue with a floating DMD in tables, which I think is a bug in 10.8 Release Candidate. Is there a way to turn it off?

**To Reproduce**
Play a table with the 10.8 Release Candidate. The DMD is visible in both Tales from the Crypt and Arabian Nights.

Tales from the Crypt (Data East 1993) VPW v1.22
TOTAN4k 1.5.vpx

https://vpuniverse.com/files/file/6933-tales-from-the-crypt-vpw-premium-data-east-1993/
https://vpuniverse.com/files/file/12652-tales-of-the-arabian-nights-4k-williams-1996/

**Expected behavior**
Not seeing weird DMD.

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/1381341/d18db040-f15a-4b4c-9c56-09812ab39c18)
![image](https://github.com/vpinball/vpinball/assets/1381341/86be98c6-16dd-4552-8e9b-9468b250feb3)

**Versions & Settings**
 - VPX: 10.8 Release Candidate
 - Windows 10
 - GPU and video settings if applicable

**Comment by francisdb** [comment]
You normally don't need this solution of you select a portrait resolution in the list. Only thing I have to do is press F11 - go to display settings - enter to reset and then adjust.

I do have issues with some pup packs showing videos in the wrong direction and had to update the pinup menu for portrait mode. Otherwise a portrait setup works great.
