### ISSUE TITLE
HDR output support

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1493]
DX9 will be out of the question (not supported).
GL via SDL3 now works (https://github.com/libsdl-org/SDL/pull/8916).
BGFX ? At least i didn't find anything easily.

**Comment by vbousquet** [comment]
Yes, I saw that too and that's an excellent news!

The move to SDL3 was planned for 10.8.1. As you said OpenGL supports it, and I think BGFX will be easy too (since it does not mess up that much with the underlying windowing API and takes what framebuffer you give him, eventually HDR).

So, it's just a matter of free time and priorisations between:
- finally finishing 10.8 (maybe it's already done ? what do we have left on this ?)
- finishing PinMame 3.6 (on my side, MM mech, some SAM things to look at, see with Jarr for B2S)
- integrate BGFX (in progress)
- move to SDL3 (had a look but not that much yet since this is a moving thing atm)

**Comment by ordes** [comment]
Considering GL provides far superior motion rendering with frame pacing and lots of us use an LG OLED screen that pumps quite a different peak brightness at HDR vs SDR, I hope HDR support for GL is the one to get attention sooner :) But, that's just my wish.
