### ISSUE TITLE
VPVR / VPX are finally in sync

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#152]
Thanks to the great work of @vbousquet we could finally close down https://github.com/vpinball/vpvr.

Links to open issues:
https://github.com/vpinball/vpvr/issues/95
https://github.com/vpinball/vpvr/issues

**Comment by vbousquet** [comment]
I will add the issue list from https://github.com/vpinball/vpvr/issues/95 here to track the fixes (I can't update the original issue since VPVR has been archived):

- [x] VPX & VPR: LUT is broken (https://github.com/vpinball/vpinball/commit/984df5b4d834eaeaf60464558559b92f3a9c44b4 => it happens that AO dither was broken in VPX < 10.8 since the dither map was overwritten by the color grade LUT, so this fixes this old bug as well),
- [ ] VPX & VPR: Some postprocess sampling offsets have to be checked (fullscreen shaders are not consistent with the use of w_h_height),
- [ ] VPX & VR: near/far plane computation is wrong (missing at least all primitive bounds and all reflections)
- [ ] VPX & VR: reflections are better, but this needs to be improved to reach the target implementation- [ ] VR: backglass has coloring/transparency issue,
- [ ] VR: DMD/Pup capture is not stable,
- [ ] VR: Bloom filter as float overflow problems,
- [ ] VR: Rendering can not be right under all point of view due to missing dynamic render ordering

**Comment by vbousquet** [comment]
Merge is now fully done, I will close this issue since things should now be followed as normal issues
