### ISSUE TITLE
Build #1935 POV Offset speed

### ISSUE THREAD

**Issue by Meshuggah70** [vpinball/vpinball#1588]
**Describe the bug**
On build #1935  POV  Vertical and Horizontal Offset are still way too touchy to dial in with any accuracy. Improvement from RC2 though
The rest of the adjustments in POV seem fine

VPX #1935  GL version, Windows 11 Home VpinMAME 3.6  #909

**Comment by aerao** [comment]
I can confirm that the bug has returned. 
However, everything was working properly again since version 1935.

I wanted to show a friend how to adjust his pov perfectly, so I launched the "screen size calibration" table, and saw that the adjustment ribbons were very small and I couldn't adjust them anymore. I went back to the VPX/cabinet Layout graphics settings, deleted the screeen (with, heigt, calibration),thinking that's where it was coming from. I restarted "screen size calibration" and that's when the bug reappeared.
I tried deleting the entire C:\Users\aerao\AppData\Roaming\VPinballX folder, but nothing changed.

**Comment by francisdb** [comment]
related issue: #1573

**Comment by francisdb** [comment]
Looking at the code the offset speed is doubled when in `Window` view mode. For `Camera` and `Legacy` it's slower.

https://github.com/vpinball/vpinball/blob/71af968e30c609a4c0fc05b97dfc3abcc457d737/LiveUI.cpp#L1274-L1275

**Comment by francisdb** [comment]
Just tested on vpinball standalone and I don't have the impression it's slowly ramping up in speed.

**Comment by Denys06** [comment]
same problem for me in 4k

**Comment by davegattis** [comment]
Same problem here. When I get to offset adjustments, it's too sensitive and requires manually editing the output file to dial it in.
10.8 RC2
