### ISSUE TITLE
10.8.0 and 10.8.1 too blurry/shifted compared to 10.7.4

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1598]
Even with MSAA, Postprocess-AA and Postprocess-sharpening off, there is a noticeable shift and somehow a weird blur or weird aliasing (depending on the table element) compared to 10.7.4.

So some shifts are still off by 0.5 or 1.5 pixels somewhere, both for GL and DX (both also differ between them in addition).

The behavior is consistent though between 10.8.0 and 10.8.1, so exists similar in both.

**Comment by toxieainc** [comment]
8.0 GL:
![grafik](https://github.com/vpinball/vpinball/assets/6709227/43fc2fbd-46c3-4e34-b2a8-01949af3e23a)
8.0 DX:
![grafik](https://github.com/vpinball/vpinball/assets/6709227/f2020939-b8cb-4c0e-9814-f575022268d3)
7.4 DX:
![grafik](https://github.com/vpinball/vpinball/assets/6709227/387f2e82-8ff0-43cc-8332-ffc21d28590e)

**Comment by toxieainc** [comment]
Builds used are latest (21.3.24).

**Comment by vbousquet** [comment]
I made some more tests on this one and I don't really get what is wrong here.
Using renderdoc on latest 10.8 from master, here is the playfield render in F7 mode (so no static prerendering, just raw render captured from renderdoc):
![image](https://github.com/vpinball/vpinball/assets/2796036/40ba2500-6631-47c8-8f5e-dc97d00ce0d5)

And this is the same capture after tonemapping (all effects off):
![image](https://github.com/vpinball/vpinball/assets/2796036/99f843cf-3a4c-4303-8258-65be4f1a51e5)

After checking, they are matching at the pixel level between the render and the post process. So the problem seems to be somewhere else than in the postprocess:
- maybe only when using the static prerendering (did you encountered this blurry issue even when using Camera mode ?)
- or maybe it's the rendering of the playfield itself which has wrong texture coordinates or something.

**Comment by vbousquet** [comment]
Found it, it's because trilinear/anistropy is used during static prerendering. I will commit a fix for this

**Comment by toxieainc** [comment]
..just verified it, thanks!
