### ISSUE TITLE
Valve Index VR View Screen Off Center

### ISSUE THREAD

**Issue by JordanJWilliams** [vpinball/vpinball#1632]
Just tried it on my Valve Index. Sadly the screen in the headset isn't centered. It's in the bottom left now. Black surrounds the off center VR view. 
It worked with VPinballX_GL 10.7.0 before.
 
It's broken on all of the 10.8 betas and both release candidates.
 
Installed GL 10.7 and it worked again.

**Comment by JordanJWilliams** [comment]
Also thank you pinball gods 🙏 ❤ 💖 😘 💓 💕

**Comment by JordanJWilliams** [comment]
Accidently closed...

**Comment by Joey-2001** [comment]
I play with the Valve Index and VR since the beginning and it works perfect and easy. So it must be a problem with your setup.
And the new tables with 10.8.0 RC2 or newer master versions look incredible.
10.7.0 is a waste of time. It's terrible against the newer versions.
We are offering help at our discord channel. So if you are interested, join our club with many tutorials and nice people.
Here is the link: https://discord.com/invite/CmCfgn3GTv

**Comment by JordanJWilliams** [comment]
> I play with the Valve Index and VR since the beginning and it works perfect and easy. So it must be a problem with your setup. And the new tables with 10.8.0 RC2 or newer master versions look incredible. 10.7.0 is a waste of time. It's terrible against the newer versions. We are offering help at our discord channel. So if you are interested, join our club with many tutorials and nice people. Here is the link: https://discord.com/invite/CmCfgn3GTv

I just drag dropped overwrite all of the old files then went to the settings and just changed the table offset to match my pincab controller. Thank you for letting me know it's on my end. I was kind of heart broken thinking it was Index in general. I joined the Discord too! Thank you for it! This is my biggest hobby and I didn't know there was a VR dedicated Discord too!

**Comment by JordanJWilliams** [comment]
studlygoorite helped (ty studlygoorite)! If supersamling isn't disabled or 100% it causes this.

**Comment by JordanJWilliams** [comment]
Closing. Thank you all so much <3
