### ISSUE TITLE
Editor: UI Could do with improvements

### ISSUE THREAD

**Issue by jaoxford** [vpinball/vpinball#1651]
**Is your feature request related to a problem? Please describe.**
I have found the UI to look very basic, I'm not sure if this is intentional or not. And I think it could do with modernisation / improvements.

**Describe the solution you'd like**
Well I suppose a more modern UI could be helpful

**Describe alternatives you've considered**
I'm aware of different front-ends for running pins. But if you ever need to come back to VPX the UI is like stepping back 20 years.

**Comment by francisdb** [comment]
I think there's work ongoing to make the tweak ui a full editor which would bring the editor to vpinball standalone on macOS/Linux.

**Comment by jaoxford** [comment]
> I think there's work ongoing to make the tweak ui a full editor which would bring the editor to vpinball standalone on macOS/Linux.

Great, where did you read this? I searched all of the issues here and couldn't find any mentions.

**Comment by francisdb** [comment]
@vbousquet @toxieainc am I correct?

**Comment by toxieainc** [comment]
Yes. Vince will know if it will/should ever become a full replacement, but so far a lot of things can be tweaked and changed within the Live UI mode.

**Comment by vbousquet** [comment]
There is no clear plan on this. Initially it was mainly an inspection tool for easier debugging. It has evolved quite a lot (especially 10.8.1) but for the time being there are lots of missing core function to make it a full UI. Anyway, now that Jason has added support for Linux/Mac, it is clearly a good candidate for a portable UI. Still, this is a very low priority thing (beside the initial inspection intent) since as dated as the existing Win32 UI can be, it is still fully functionnal.
