### ISSUE TITLE
Android Table Crash on Start

### ISSUE THREAD

**Issue by johnnyzen** [vpinball/vpinball#1707]
Various table crashes on start up.

Maybe not doing something right?

Device: Odin 2 Base Model
APK: 10.8.0-1953-a4852aa
OS: Android 13

Please see attached log. Hope this helps.

[vpinball.log](https://github.com/vpinball/vpinball/files/15225586/vpinball.log)

**Comment by francisdb** [comment]
Are you using the patched script from https://github.com/jsm174/vpx-standalone-scripts/tree/master/Star%20Trek%20(Bally%201979)%202.1.1 ?

That should fix the script issues. Just put the .vbs file next to the .vpx file and make sure they have the same name.

https://github.com/jsm174/vpx-standalone-scripts contains patches for many tables, they are required because standalone uses a different vbscript engine that has some issues.

**Comment by johnnyzen** [comment]
Thanks @francisdb, I have added vbs for this, but the same result. From the new log, I dont see anything about picking up the vbs file? So not sure if system not using. Doubled checked file names.

New Log
[vpinball.log](https://github.com/vpinball/vpinball/files/15226316/vpinball.log)

**Comment by johnnyzen** [comment]
aha, I placed the vbs script in the Scripts folder instead of the Tables folder. And its working!!!!!!

Thank you so much for your help. :)

**Comment by johnnyzen** [comment]
Thank you for your great work.
