### ISSUE TITLE
VPX on Android won't run tables.

### ISSUE THREAD

**Issue by PeterTucker** [vpinball/vpinball#1729]
**Describe the bug**
Connected web server. I put my vpx tables in the tables folder. Roms in vpinmame/roms folder. It will not play any games. Only shows a black screen when I launch a table. Only game I got to run is Street Fighter 2. When I put in coins in SF2 it makes the "coin sound," but the DMD credits don't update, and I can't press start.

**Versions & Settings**
VPinballX_GL-10.8.0-1954-f3b67b1-Release-android-arm64-v8a
Quest 3

**Comment by jsm174** [comment]
*Note:* If your bug is in **ANY WAY** related to Visual Pinball Standalone, first seek support on the [Virtual Pinball Chat Discord Server](https://discord.com/invite/YHcBrtT), channel `#vpx-standalone`. If your table immediately crashes on launch, please refer to [here](https://github.com/jsm174/vpx-standalone-scripts) and [here](https://github.com/vpinball/vpinball/blob/standalone/standalone/vbscript.md).

**Comment by Strike50ball** [comment]
Webserver not shows me folders (tables,pinmame,etc.)

![Image](https://github.com/user-attachments/assets/d90d4c1a-6f64-45ec-860d-87fb02fcbf16)

Help me pls somebody...

**Comment by pinkykaras** [comment]
you need to create this folders self

**Comment by pinkykaras** [comment]
this long number folders are your tabels that you imported

**Comment by jsm174** [comment]
There are numerous references to finding help directly in the app. 

But you can also look here:

https://github.com/vpinball/vpinball/blob/master/standalone/docs/ios/README.md

iOS and Android are pretty much identical.

**Comment by pinkykaras** [comment]
you ned to create - pinmame and in pinmame roms folder ,🤪
