### ISSUE TITLE
VPX RC4 texture problem with THING on TAF table by VPW

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#1824]
I have a texture problem with black lines on TAF table by VPW using VPX RC4 GL version.
Please check the attached photo.

Is there any buffer or cache to clean?
I have several friends with very similar setupt without this problem. My video card is nvidia RTX 3080. I do not have any other problem like this on other tables.

![Screenshot_417](https://github.com/vpinball/vpinball/assets/119076983/babadcaa-d0d3-48b8-affc-2e9fe8636f0a)

**Comment by Meshuggah70** [comment]
easy fix by turning screen space reflections off or down. use live editor to adjust the lighting.. not rreally a 10.8 or a RC4 issue

**Comment by dacstyle** [comment]
> easy fix by turning screen space reflections off or down. use live editor to adjust the lighting.. not rreally a 10.8 or a RC4 issue

Thanks for your help.
I tried disabling "Max ambient occlusion" and "max reflection mode" but the issue still persist.

Maybe you mean some different setting and I'm missing the correct option?

**Comment by mikelaz** [comment]
Hi Team,

I have the same issue with Thing in RC4 GL and I have also discovered the same black dot problems on the following tables: 
- The Flintstones (G5K)
- Tron Legacy (VPW)

The issues do not happen on RC4 DX

I share some screenshots just in case they could be helpful

Thanks for your help and your work in this project!

![Flintstones](https://github.com/user-attachments/assets/b9f415af-60ed-4c96-b8c3-c3335478708e)
![tron_legacy_1](https://github.com/user-attachments/assets/eb3e8a70-29ec-4b22-a3fc-fba434a7504c)
![tron_legacy_2](https://github.com/user-attachments/assets/0a4e170b-b967-4df9-89c1-628b6b489085)

**Comment by dacstyle** [comment]
Yes, I also have the problem on The Flinstones.

I did not checked Tron yet, but I will.

**Comment by dacstyle** [comment]
Same problem with TRON

**Comment by Meshuggah70** [comment]
I have all these tables and have adjusted them all with live edit  . (Adjusting ambient occlusion and screen space reflections ). Still none of them have that issue with me..

**Comment by dacstyle** [comment]
Could you please provide us with a step-by-step guide on how to solve this problem?
I am not experienced with the live editor, and I have been unable to find a solution there.

**Comment by Meshuggah70** [comment]
You can also just uncheck Ambient occlusion and screen space reflections in
VPX settings will make it go away without adjusting. But I just like a
little of both that's why I use Live editor. Adds a little detail to the
table rather than turning it off .   But here is how to live edit.....with
a table running hit .Q then live editor. push play button in left corner.
insert coins. start table.. adjust all parameters how you want (+ and _
tabs for each). when done with each parameter press the square disk button
to the right for each(it's almost off the screen). after completed hit stop
button it will go back to VPX main screen of table loaded then hit pulldown
and hit save.. all done ** if AO and Screen space reflect boxes are not
checked those 2 values will have any effect editing*"

**Comment by Meshuggah70** [comment]
disable the screen space reflections (It's abbreviated) below it I bet it
goes away

**Comment by dacstyle** [comment]
Thanks, mate. I solved the problem.

For anyone who has the same issue, just uncheck the following option:

![Uploading 20240821_001923.jpg…]()

**Comment by dacstyle** [comment]
![20240821_001923](https://github.com/user-attachments/assets/a60ce2b2-af6c-432d-b451-d59fd53e8d24)
