### ISSUE TITLE
VPX VR .572 B2S is not scaled to the backglass primative

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpinball#191]
**Describe the bug**
10.8.572 GL for VR is capturing the backlass however its not scaled correctly to the backglass primitive. It will show still bright white for the backglass primitive. I have included pictures with the backglass primitive hidden so can see the scalling issue better.

**To Reproduce**
Run in vr with B2S capture enabled.

**Expected behavior**
B2S shown properly

**Screenshots**
![20221114_114608](https://user-images.githubusercontent.com/23017535/201741728-001c893f-1d1d-477b-8ce0-bf676b2878da.jpg)
![20221114_114614](https://user-images.githubusercontent.com/23017535/201741748-4583d88d-e101-4357-adb9-ad863a5d8c0d.jpg)

**Versions**
 - VPX: 32 bit 10.8.572
 - Windows 10
 - RTX 3080

**Comment by camokarzi** [comment]
Yes I got the same, only option was to remove the B2S file altogether making DOF useless

**Comment by gear323** [comment]
Lethal weapon 3 by VPW shows two backglasses.   One off-center like this one and one in the correct place.  The off-center one is also forward and blocks the DMD.  I have B2S disabled as well as capture of backglass and DMD disabled.

**Comment by psiomicron** [comment]
Try moving the lethal weapon B2S to another folder, or delete it. It won't
give you the animated backglass but that might be a temp fix until they try
to resolve this bug.

**Comment by gear323** [comment]
Hi psiomicron,

That does indeed work.  I thought that since I had B2S disabled and I was not capturing the backglass or dmd etc. that this would not be a workaround but it did indeed remove the duplicate backglass and it looks fine now. 

Thanks for the Tip!

**Comment by psiomicron** [comment]
So it seems that the new version is programed to load an object that acts like a backglass, that captures the desktop, if b2s is there. Would it be possible for the code to search for the primitive that as the file "Backglassimage" associated to it and then take the size and position of the primitive and set the new object to those parameters. This would help also with tables like Baby Pacman where the backglass is not in the same place as a regular table.

**Comment by Joey-2001** [comment]
It's nice, to have the external backglass again. I made many vr-tables with the external. But I can't upload them, because it works different from former versions. In the older versions, you need a primitive with an image named "backglassimage".
There are the backglass displayed in the same size and at the same position like the backglassimage. So it was easy, to change the position or scaling.
I don't find something like that with the new version. It's also possible, to delete the primitive with the image and the backglass work; but with wrong scaling.
I record a short video of the start of the last actual version 589. As you see, after the start the external backglass is shown for a second. Then it falls to the back and change to a white image and the new backglass with wrong scaling appears.
https://youtube.com/shorts/TlQ839E9uBE

**Comment by psiomicron** [comment]
Ok it seems like it is working, now it's just brighter that what it should
almost to the point the colors are getting close to being washed out. Star
Trek the Next Generation table is a good example.
