### ISSUE TITLE
Assertion Failed error "channels_in_file == 3 || channels_in_file == 4"

### ISSUE THREAD

**Issue by jimbeauphloyd** [vpinball/vpinball#196]
Error occurs when loading some tables before the table is played. Started happening on 10.7.2 with a clean install.

```
assertion failed
program:d:\a\vpinball\visuall\vpinball.exe
File:D\a\vpinball
vpinball\texture.cpp
Line 517

Expression: channels_in_file == 3 || channels_in_file == 4
```

Tables that I have gotten the error on:

Stranger Things (Stranger Edition): https://orbitalpin.com/downloads/
Gorgon
TOTAN 4K: https://vpdb.io/games
Super Mario Brothers
Dukes of Hazzard: https://vpuniverse.com/files/file/11716-dukes-of-hazzard-pinball-2022-table-and-puppack/
Bone Busters
Funhouse
Indiana Jones the Pinball Adventure: https://vpuniverse.com/files/file/8568-indiana-jones-the-pinball-adventure-williams-1993-vpwmod/
Junkyard
NBA Fastbreak: https://vpuniverse.com/files/file/6524-nba-fastbreak-bally-1997-vpw-mod/
Nemesis
Safe Cracker
Scared Stiff
Sonic the Hedgehog
Strikes and Spares
Teenage Mutant Ninja Turtles
Waterworld

**Comment by toxieainc** [comment]
Seems like you're using a debug build instead of a release build, so please use https://github.com/vpinball/vpinball/releases/download/v10.7.2-366-f94da1e/Main.Download.Minimal.-.VPinballX72_Minimal.zip

Also, the assertion you found was already fixed by https://github.com/vpinball/vpinball/commit/3d805aa20fbdacb2f3b7b74dfda7bea9cc766b6d

But thanks for the report!
