### ISSUE TITLE
Altered illumination colors: WCG and Tonemapper issues?

### ISSUE THREAD

**Issue by KrakenByteKraken** [vpinball/vpinball#2001]
The colors on some tables have changed in their general illumination.

I noticed this issue a few versions before, but I don't remember. Now it appears with all VP flavors: DX9 (_VPinballX-10.8.1-2693-a741768-Release-win-x64.zip_), GL (_VPinballX_GL-10.8.1-2693-a741768-Release-win-x64.zip_) and BGFX (_VPinballX_BGFX-10.8.1-2693-a741768-Release-win-x64.zip_; backends used: OpenGL, Direct3D11; it crashes going to bank and then into desktop in Vulkan and Direct3D12) all of them in both x86 and x64 versions.

![VPinballX_BGFX64_2024_11_09_13_07_50_520](https://github.com/user-attachments/assets/4c7040cb-407d-4dc5-bfbf-98ce792a2249)

The **[Twilight Zone (Bally 1993) VPW Edition](https://vpuniverse.com/files/file/20930-twilight-zone-bally-1993-vpw-edition/)**  goes wrong in DX11.

![VPinballX_BGFX64_2024_11_09_13_22_35_446](https://github.com/user-attachments/assets/0d8c2493-d504-44ca-a9f2-c2af7c968dcf)

And it also goes wrong in GL.

Also, I tried the standard release versions (_VPinballX_GL-10.8.0-2030-86cf32a-Release-win-x64.zip_) with the same sad results. And in a new attempt, I tried on another PC, but it always went bad:

![VPinballX_BGFX64_2024_11_09_08_49_47_858](https://github.com/user-attachments/assets/b0abe49a-8ae7-450b-addf-8a28c9c38cdf)

Then I found that some tables go right, so: Could this behavior be part of the table build instead of the new VP versions?

![VPinballX_BGFX64_2024_11_09_08_48_17_058](https://github.com/user-attachments/assets/50d711a8-b34f-499f-bba5-e37efa35f9e9)

![VPinballX_BGFX64_2024_11_09_08_50_47_544](https://github.com/user-attachments/assets/dae8be46-665e-4c94-afeb-987db67f9d63)

![VPinballX_BGFX64_2024_11_09_08_52_11_654](https://github.com/user-attachments/assets/8aa84ec5-feb5-47df-ab9c-bb56bfee4709)

![VPinballX_BGFX64_2024_11_09_08_56_56_923](https://github.com/user-attachments/assets/6894cda0-e4b9-47f5-844d-00b688346eab)

Or are there altered illumination colors because there is an WCG and Tonemapper issue? I don't know.

Another question is that I have all versions coliving in the same folder (I renamed the 10.8.0 versions to different names), but I don't know if this could be the reason for this problem because I also tried to decompress the zip files into new independent folders. Who knows?

**Comment by KrakenByteKraken** [comment]
More examples of tables that have their illumination wrong, they're working with lighting issues:

![VPinballX_GL64108_2024_11_09_14_56_31_014](https://github.com/user-attachments/assets/2f62cc31-7473-4d36-bd1b-bbbcb0da2ba5)
 **[Bad Cats (Williams 1989) VPW Mod](https://vpuniverse.com/files/file/6529-bad-cats-williams-1989-vpw-mod/)**


![VPinballX_GL64108_2024_11_09_15_02_35_957](https://github.com/user-attachments/assets/03d4037b-f295-4097-92b7-e42fd33c4a15)
**[The Flintstones](https://vpuniverse.com/files/file/8763-the-flintstones/)**


![VPinballX_GL64108_2024_11_09_15_03_50_428](https://github.com/user-attachments/assets/8d8b0337-acd8-4a5a-9428-97d1fb190d71)
 **[Getaway,The-Highspeed II (MOD) nFozzy, Fleep Sounds, LUT](https://vpuniverse.com/files/file/9917-getawaythe-highspeed-ii-mod-nfozzy-fleep-sounds-lut/)** 


![VPinballX_GL64108_2024_11_09_15_10_32_445](https://github.com/user-attachments/assets/de166cba-5515-48f9-8ff8-3a64c1490c44)
 **[Jurassic Park (Data East 1993) VPW](https://vpuniverse.com/files/file/20053-jurassic-park-data-east-1993-vpw/)** 


![VPinballX_GL64108_2024_11_09_15_13_11_631](https://github.com/user-attachments/assets/c572b99d-7916-4dd4-8250-056a0a8b58a0)
 **[Scared Stiff (Bally 1996) Mikcab_Mod](https://vpuniverse.com/files/file/13544-scared-stiff-bally-1996-mikcab_mod/)** 


Also, another tables that aren't so evident, the lighting differences are not so significant, but they are wrong too:

![VPinballX_GL64108_2024_11_09_14_53_25_341](https://github.com/user-attachments/assets/cce22a5e-c0ae-4937-92ef-fdac23937f2f)
 **[ACDC LUCI (Stern 2013) VPW Mod](https://vpuniverse.com/files/file/12471-acdc-luci-stern-2013-vpw-mod/page/6/?tab=comments#comment-63863)** 


![VPinballX_GL64108_2024_11_09_14_57_36_479](https://github.com/user-attachments/assets/25d27a29-25de-450f-8fe0-a346ea3f3dec)
 **[Ripley's Believe It or Not! (Stern 2004) VPW Mod](https://vpuniverse.com/files/file/18488-ripleys-believe-it-or-not-stern-2004-vpw-mod/page/5/?tab=comments#comment-76876)** 


![VPinballX_GL64108_2024_11_09_14_58_13_657](https://github.com/user-attachments/assets/7111f869-b5f1-472d-9ccf-b41dfef66f47)
 **[Big Bang Bar (Capcom 1996) VPW](https://vpuniverse.com/files/file/13634-big-bang-bar-capcom-1996-vpw/)** 


![VPinballX_GL64108_2024_11_09_14_58_50_364](https://github.com/user-attachments/assets/bfe1d89f-eedb-4da7-8eaf-9e981f995ce0)
 **[Cactus Canyon (& Continued) (Bally 1998) VPW Mod](https://vpuniverse.com/files/file/6267-cactus-canyon-continued-bally-1998-vpw-mod/page/8/?tab=comments#comment-68062)** 


![VPinballX_GL64108_2024_11_09_14_59_24_662](https://github.com/user-attachments/assets/a9da71c9-3c0f-46e3-9e4b-c7d86af93524)
 **[Creature From The Black Lagoon (Bally 1992)](https://vpuniverse.com/files/file/6110-creature-from-the-black-lagoon-bally-1992/)** 


![VPinballX_GL64108_2024_11_09_15_04_31_327](https://github.com/user-attachments/assets/b2d2ae48-5b26-4399-8b24-2db21a8fd752)
**[Godzilla (Sega 1998) VPW](https://vpuniverse.com/files/file/15933-godzilla-sega-1998-vpw/)** 


![VPinballX_GL64108_2024_11_09_15_11_14_407](https://github.com/user-attachments/assets/589dfa1d-e8f9-464b-832d-e532b61c5a10)
 **[Lord of the Rings Valinor Edition (Stern 2003) VPW](https://vpuniverse.com/files/file/8828-lord-of-the-rings-valinor-edition-stern-2003-vpw/)** 


![VPinballX_GL64108_2024_11_09_15_11_53_084](https://github.com/user-attachments/assets/d016b0cb-09f4-4aba-adb7-6de717f697da)
 **[Medieval Madness (MOD) nFozzy, Fleep Sounds, LUT 1.1](https://vpuniverse.com/files/file/9784-medieval-madness-mod-nfozzy-fleep-sounds-lut-11/)** 


![VPinballX_GL64108_2024_11_09_15_12_27_017](https://github.com/user-attachments/assets/a83c13a3-f30a-45b2-8cdf-5602ebe62278)
 **[Monster Bash (Williams 1998) VPWmod](https://vpuniverse.com/files/file/9091-monster-bash-williams-1998-vpwmod/)** 


![VPinballX_GL64108_2024_11_09_15_17_06_894](https://github.com/user-attachments/assets/2e8a4b59-fec7-438d-8140-05705072ff7f)
 **[Star Trek The Next Generation (Williams 1993) VPW Mod](https://vpuniverse.com/files/file/13319-star-trek-the-next-generation-williams-1993-vpw-mod/)**

**Comment by KrakenByteKraken** [comment]
It also happens in VR:

![20241110_122821_MixedReality](https://github.com/user-attachments/assets/7591af65-23bf-4e9b-b519-0807d5a9b10c)

**Comment by toxieainc** [comment]
Do you own a HDR capable monitor?

**Comment by toxieainc** [comment]
Or do these use the TonyMcMapFace tonemapper originally? @vbousquet Is that one automatically remapped to AgX now?

**Comment by KrakenByteKraken** [comment]
> Do you own a HDR capable monitor?

One PC is running with HDR capable monitor (Asus ROG Swift PG43UQ 43" LED UltraHD 4K 144Hz HDR G-Sync Compatible) but it happens always in both cases: when HDR is ON or OFF. On the other side, my older PC is operating with a SDR monitor (Samsung  23" LED TV 3D S23A750D) and the issue is exactly the same.

**Comment by KrakenByteKraken** [comment]
> Or do these use the TonyMcMapFace tonemapper originally? @vbousquet Is that one automatically remapped to AgX now?

Because the issue happens with all my PCs (older and newest), I suppose it could be related to the new tonemapper system but I can't confirm it. Shall you?

**Comment by KrakenByteKraken** [comment]
Thank you for your advice. I'll try to clean the folder and remain only one version (10.8.0) and then I'll open a new folder for the newest (10.8.1) because I enjoy playing like a test driver. I'll report soon if that problems go away doing this. Thanks!

**Comment by PinBob100** [comment]
Thanks for the detailed description of the issue. I just wanted to quickly report that I have exactly the same problem with the exact same tables. Thanks for looking into it!

**Comment by KrakenByteKraken** [comment]
Do anybody have any idea or instructions for testing this in the safe way?

I cleaned all the folders and installed one VPX version only per folder even separated of VPinMame, but the issue persist anyway.

It's a little crazy because now I can't make it works fine even with 10.8.0 Release Candidate 5 or 4, which they had worked fine in the past.

Is something corrupted somewhere or is there missing setting in my config?

I tried to delete the cache in %appdata% and remove settings in windows registry but finishing with the same unsuccessful results.

It's sad but, at last, I'm not alone. Isn't it, @PinBob100 ?

Anyway, thanks everybody very much for your time. Regards.

**Comment by PinBob100** [comment]
I also tried KrakenByteKraken's fixes but no luck.

**Comment by KrakenByteKraken** [comment]
Now, I wonder: **What is, nowadays, the right procedure to install VPX from scratch**?

I thought that was starting with the [version 10.7.2 EXE installer](https://github.com/vpinball/vpinball/releases/download/v10.7.2-366-f94da1e/Main.Download.Installer.-.VPX72setup.exe), then we must overwrite all the files with the [10.7.3 version](https://github.com/vpinball/vpinball/releases/tag/10.7.3), and after with [10.7.4 files](https://github.com/vpinball/vpinball/releases/tag/v10.7.4-433-a4c3788). OK, easy-peasy. After that, we've got a DX9 flavor only version.

I thought then we must start with 10.8.0 versions, but I supposed I must overwrite that previous installation with the files of [10.8.0 RC 5](https://github.com/vpinball/vpinball/releases/tag/v10.8.0-2015-6f63503) (DX9 x86 flavor) edition. Isn't it?

But, what happens if I want to try other flavors, like GL x64 or BGFX x64? What must I do? Is there any tutorial anywhere (like the excellent [64bit VPX Pincab Setup Guide](https://github.com/vpinball/b2s-backglass/wiki/64bit-VPX-Pincab-Setup-Guide)) to accomplish this another challenge?

Please, any clue will be appreciated. Thank you so much.

**Comment by KrakenByteKraken** [comment]
I found this tutorial about how to [Manually updating VPX, VPinMAME and B2S server](https://vpuniverse.com/tutorials/article/39-manually-updating-vpx-vpinmame-and-b2s-server/) (updated in November 2024, this current month) and, as you can see, is based in the same method I followed previously with unsuccessful results, so I don't know how to follow now. Any clue?

**Comment by PinBob100** [comment]
I observed something peculiar. I updated LoadedWeapons Theater of Magic. I started the table and everything was nomal. But when I started the table again, the lighting was broken. I assumed that a table specific flag or setting was changed when launching the table the second time. So I deleted ToMs registry settings, NV RAM and the cfg file (kind of desperate things to do, I know) . But unfortunately all that was futile. A total mess. I do not have any idea anymore where to look for the culprit setting. Of course I tried all possible settings in VPX. Might be an "orphaned" flag/setting, hidden somewhere in the registry. That is the only explanation why new installs don't work.

Any helpful hint would be greatly appreciated,

**Comment by KrakenByteKraken** [comment]
**I finally fixed it!!!** I'm not sure, but it looks like it was some kind of **VPinMAME weird interference with VPinballX**.

After I did the experiment proposed by @PinBob100, I noticed that something was wrong with the loading times of VPinMAME and, as was before said by @vbousquet: it's better that VPinMAME must be in a separated folder.

Firstly, **I collected all critical folders from VPinballX and VPinMAME for not losing them**, like: TABLES, MUSIC, ALTCOLOR,  ALTSOUND, CFG,  MEMCARD, NVRAM, ROMS, SAMPLES, SNAP...

Then, **I uninstalled everything about VPX 10.7.4 and older**. And after, I became to install only one instance of VPX per folder (BGFX in my case, because it uses the little newer DX11 and multithreaded process to decrease lag).

And I made another **new folder for VPinMAME separated from VPX**. Into this VPinMAME, I installed DMD-Extensions and FlexDMD. 

After that, it starts to work fine, and I noticed that now the tables use by default the newest AgX tonemapper as expected, but I prefer Reinhard tonemapper for some tables.

![VPinballX_BGFX-10 8 1 WORKING FINE](https://github.com/user-attachments/assets/2902cf1e-f507-473a-8817-54d00374c682)

After all this mess, I can finally can enjoy this again. **Thank you everybody!!!**

Regards!

**Comment by PinBob100** [comment]
Awesome!!! Congratulations!!! Thanks for your persistence!!

I still have a few questions so I can replicate your success:

1. Uninstalling

Is there a correct method to uninstall the existing VPinball. I.e. do I only have to run "Uninstall" from Settings\Apps\Installed Apps? Or is there more to it?

2. Reinstalling

If I understood you correctly I would install using the following folder structure (I used Baller Installer initially):

VPinball in C:\vPinball\VisualPinball\
B2SServer in C:\vPinball\VisualPinball\B2SServer\
VPinMAME in C:\vPinball\VPinMAME\
DMDExt in C:\vPinball\VPinMAME\
FlexDMD in C:\vPinball\VPinMAME\

Note: In my current setup VPinMAME is in VisualPinball\VPinMAME\   So it is in a separate folder!?

Thanks again and kind regards!

**Comment by PinBob100** [comment]
Got it working again following your advice. Different from original plan, I moved B2SServer outside of VisuaPinball folder to  C:\vPinball\

I also set up seperate folders for the different VPX versions. 10.8.0 works fine, 10.8.1 BGFX is not working properly, (video/image freezes).

**Comment by KrakenByteKraken** [comment]
You're welcome.

First, I'll try to answer your questions:

**1. Uninstalling**
I really don't know which is the right recommended procedure to uninstall the existing VPinballX, I can tell you what I did but remember I don't know if it's well done: I ran "Uninstall" from old VPinballX folder that stay there from v10.7.2 (and the new releases don't come with it). Previously, always remember to extract the critical folders (tables, roms, etc...) to avoid any loss. In the middle of the mess, I was desperate and also try to delete everything related to VPinballX, it means "%appdata%\Roaming\VPinballX" and remove all keys with Windows Registry (regedit.exe) searching and deleting all I could found relative to: "\HKEY_CURRENT_USER\Software\Visual Pinball".

Then I also remove any orphan folder into VPinballX and the main VPinballX folder itself too.


**2. Reinstalling**
I tried Baller Installer sometime ago. It has awesome and very useful features like automatic updates, and it's the recommended way for rookies. But I was a Virtual Pinball Player a long time before the first Baller Installer was released, so I went by the older and harder manual way like always I did.

Historically, VPinballX was an only DX9 x86 program which come with VPinMAME and B2SServer into its own folder (as you said in your example). After years of development, the different pieces of this pie are going step by step splitting from VPinballX, assembled but not mixed, and they can work in it different own folder for each one. For that, I suggest you the folder structure I followed: 

- BGFX flavored Visual Pinball:
C:\VirtualPinball\VPinballX-BGFX-x64

- OpenGL flavored Visual Pinball:
C:\VirtualPinball\VPinballX-GL-x64

- OpenGL flavored Visual Pinball:
C:\VirtualPinball\VPinballX-GL-x86

- DirectX 9 flavored Visual Pinball:
C:\VirtualPinball\VPinballX

- B2SBackglassServer:
C:\VirtualPinball\B2SBackglassServer

- VPinMAME mixed with DMDExt and FlexDMD:
C:\VirtualPinball\VPinMAME

- VPinSPA:
C:\VirtualPinball\VPinSPA

- Tables:
C:\VirtualPinball\Tables

It fixes our problem with colors, and keep the possibility to use different flavors; but I'm still testing it. I'm now working in progress with these folders:

- PinUPSystem:
C:\VirtualPinball\PinUPSystem

- DirectOutput:
C:\VirtualPinball\DirectOutput

- Music:
C:\VirtualPinball\Music

Perhaps I'll must move Music into VPinballX again, but I'll test to see what happens.

Once said that, my own thoughts are that **in the near future I'll go full ahead with ONLY the BGFX x64 flavor** because It can use many other graphics backends, and they're upgrading it to add VR support through OpenXR. When it will be finished then will be only **one ~Ring~ VPinballX to rule them all**, well you know... 😉

**Comment by KrakenByteKraken** [comment]
Anyway, congratulations on the repairing.

Happy to know you fixed it too. Well done!!! 😎

**Comment by PinBob100** [comment]
Hi KrakenByte:

 

Thanks for your detailed reply. It seems that you wrote your mail while I just finished fixing the problem. I think I am going to archive your mail in case I need to uninstall again (or somebody else runs into the same problem).

 

I pretty much did what you did. But I forgot to remove the files in %appdata%.

 

The key to success though appears to be uninstalling VPinMAME. I believe the problem started with a recent VPinMAME version. I had the problem that VPX crashed upon exiting (so did exiting the ROM tests of the MAME setup program). I had to revert to version 1122.

 

Music must be in the folder with the exe file it appears. I tried a link but that does not work. If you find a way, please let me know!

 

VPinSPA I left in the VPinMAME folder since it requires an x86 bass.dll. But I shall  try to move it out of there. Makes things better structured and more transparent.

 

And each VPX flavor now has its separate folders.

 

Unfortunately I do not get the BGFX version to work. But I currently have little motivation left to investigate what is wrong with it. Maybe deleting the files in appdata helps.

 

Thanks again for your support. Without your persistence I could not have fixed it.

 

Sincerely

 

Robert

 

 

 

Von: KrakenByte ***@***.***> 
Gesendet: Montag, 18. November 2024 12:31
An: vpinball/vpinball ***@***.***>
Cc: PinBob100 ***@***.***>; Mention ***@***.***>
Betreff: Re: [vpinball/vpinball] Altered illumination colors: WCG and Tonemapper issues? (Issue #2001)

 

You're welcome.

First, I'll try to answer your questions:

1. Uninstalling
I really don't know which is the right recommended procedure to uninstall the existing VPinballX, I can tell you what I did but remember I don't know if it's well done: I ran "Uninstall" from old VPinballX folder that stay there from v10.7.2 (and the new releases don't come with it). Previously, always remember to extract the critical folders (tables, roms, etc...) to avoid any loss. In the middle of the mess, I was desperate and also try to delete everything related to VPinballX, it means "%appdata%\Roaming\VPinballX" and remove all keys with Windows Registry (regedit.exe) searching and deleting all I could found relative to: "\HKEY_CURRENT_USER\Software\Visual Pinball".

Then I also remove any orphan folder into VPinballX and the main VPinballX folder itself too.

2. Reinstalling
I tried Baller Installer sometime ago. It has awesome and very useful features like automatic updates, and it's the recommended way for rookies. But I was a Virtual Pinball Player a long time before the first Baller Installer was released, so I went by the older and harder manual way like always I did.

Historically, VPinballX was an only DX9 x86 program which come with VPinMAME and B2SServer into its own folder (as you said in your example). After years of development, the different pieces of this pie are going step by step splitting from VPinballX, assembled but not mixed, and they can work in it different own folder for each one. For that, I suggest you the folder structure I followed:

*	BGFX flavored Visual Pinball:
C:\VirtualPinball\VPinballX-BGFX-x64
*	OpenGL flavored Visual Pinball:
C:\VirtualPinball\VPinballX-GL-x64
*	OpenGL flavored Visual Pinball:
C:\VirtualPinball\VPinballX-GL-x86
*	DirectX 9 flavored Visual Pinball:
C:\VirtualPinball\VPinballX
*	B2SBackglassServer:
C:\VirtualPinball\B2SBackglassServer
*	VPinMAME mixed with DMDExt and FlexDMD:
C:\VirtualPinball\VPinMAME
*	VPinSPA:
C:\VirtualPinball\VPinSPA
*	Tables:
C:\VirtualPinball\Tables

It fixes our problem with colors, and keep the possibility to use different flavors; but I'm still testing it. I'm now working in progress with these folders:

*	PinUPSystem:
C:\VirtualPinball\PinUPSystem
*	DirectOutput:
C:\VirtualPinball\DirectOutput
*	Music:
C:\VirtualPinball\Music

Perhaps I'll must move Music into VPinballX again, but I'll test to see what happens.

Once said that, my own thoughts are that in the near future I'll go full ahead with ONLY the BGFX x64 flavor because It can use many other graphics backends, and they're upgrading it to add VR support through OpenXR. When it will be finished then will be only one Ring VPinballX to rule them all, well you know... 😉

**Comment by KrakenByteKraken** [comment]
You are welcome @PinBob100 , with pleasure, and thank you for your pretty words. I'm pleased to know that I could be helpful to other people.

I agree with you: The key to success probably was to uninstall the old VPinMAME integrated originally into VPinballX. It seems like appears one interference between it and VPinballX.

Talking about folders, yes, "Music" must be like you said, or it will not work. So let it stay with the VPinballX EXE. I'll try to do more testing to keep it apart like "Tables" folder, but if no success, I'll propose it as an improvement for the next version or as a new feature.

VPinSPA was a controversial program from the day it was made, as everybody knows. I prefer to keep it working in parallel with VPinMAME and run the Windows registry key commands to make it x64 compatible (as you can see in [the Reddit forum](https://www.reddit.com/r/virtualpinball/comments/12q83dd/cant_load_spa/)). But I'm interested in how do you do this, mixing it with VPinMAME, isn't it? Please, explain it to me, it could be an improvement.

The BGFX version is so experimental and unstable for now. I found it crashes with PinUPSystem when PinUPPlayer tables start from PinUPPopper front end. So, after think about that, I went back to 10.8.0 GL x64 to stay in the more stable system, for now, for playing in cabinet and VR.

Anyway, thank you, Robert, again for your collaboration and everybody working in this awesome hobby.

Best regards,

**KrakenByte**

**Comment by PinBob100** [comment]
Hi again KrakenByte,

 

thanks for the reply and the detailed input. I am a little desperate again since I encountered new problems. I keep getting script errors and I also have problems with PuPpacks. Additionally I could no get VPinSPA to work. It seems I have to start over again. This time I will keep VPinMAME in the respective VPX folder. Tables folder outside of VPX folder is in my opinion a smart thing to do so I will leave it there. Same with B2SServer. It would be nice if there is a way to relocate the music folder e.g. to the tables folder.

 

Will keep you posted. Still curious if I am the only one with this odd behavior.

 

Regards

 

Robert

 

Von: KrakenByte ***@***.***> 
Gesendet: Dienstag, 19. November 2024 10:03
An: vpinball/vpinball ***@***.***>
Cc: PinBob100 ***@***.***>; Mention ***@***.***>
Betreff: Re: [vpinball/vpinball] Altered illumination colors: WCG and Tonemapper issues? (Issue #2001)

 

You are welcome @PinBob100 <https://github.com/PinBob100>  , with pleasure, and thank you for your pretty words. I'm pleased to know that I could be helpful to other people.

I agree with you: The key to success probably was to uninstall the old VPinMAME integrated originally into VPinballX. It seems like appears one interference between it and VPinballX.

Talking about folders, yes, "Music" must be like you said, or it will not work. So let it stay with the VPinballX EXE. I'll try to do more testing to keep it apart like "Tables" folder, but if no success, I'll propose it as an improvement for the next version or as a new feature.

VPinSPA was a controversial program from the day it was made, as everybody knows. I prefer to keep it working in parallel with VPinMAME and run the Windows registry key commands to make it x64 compatible (as you can see in the Reddit forum <https://www.reddit.com/r/virtualpinball/comments/12q83dd/cant_load_spa/> ). But I'm interested in how do you do this, mixing it with VPinMAME, isn't it? Please, explain it to me, it could be an improvement.

The BGFX version is so experimental and unstable for now. I found it crashes with PinUPSystem when PinUPPlayer tables start from PinUPPopper front end. So, after think about that, I went back to 10.8.0 GL x64 to stay in the more stable system, for now, for playing in cabinet and VR.

Anyway, thank you, Robert, again for your collaboration and everybody working in this awesome hobby.

Best regards,

KrakenByte

**Comment by KrakenByteKraken** [comment]
Hi, Robert.

In my case, I solved the PuPpacks problems going back to 10.8.0. Perhaps 10.8.1 version need still more development work.

It looks like VPinSPA have an erratic behavior that requires install it first and just after install VPinMAME again. I have them, as you've can see, in different folders but not one inside the other.

I suggest starting using the x86 flavors, like it was made, and when it'll be working then use the Windows registry trick to make it x64 compatible.

The "Music" folder seems to be blocked by software design because it doesn't work if you move it to any other place. Maybe could be a good idea to make an option in the VPX menus to choose Music folder like other environment variables, but it'll be a developer decision.

Regards,
**KrakenByte**

**Comment by PinBob100** [comment]
One final comment: I got VPinSPA to work

I put the files here:

VPinMAME\InstallVPinSPA.exe
VPinMAME\VPinSPA.dll
VPinMAME\Bass.dll
VPinMAME\spagb\gbnv.txt
VPinMAME\spagb\image.bin
VPinMAME\spagb\spagb_100.cRZ
VPinMAME\spagb\SternGB.dll

Then I uninstalled and reinstalled VPinSPA.

Next I added the registry settings to x64 VPX uses 32 bit VPinSPA:

reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v AppID /t REG_SZ /d "{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"

reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"

reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v DllSurrogate /t REG_SZ

Hope this helps.

**Comment by KrakenByteKraken** [comment]
Congratulations!!! Pleased to know that you made it too!!!

I did it in a way so similar. The only difference I see is that I've got VPinSPA into another folder but outside the VPinMAME folder:

- VPinMAME mixed with DMD-Extensions and FlexDMD:
C:\VirtualPinball\VPinMAME
C:\VirtualPinball\VPinMAME\altcolor\spagb_100\spagb_100.cRZ

- VPinSPA:
C:\VirtualPinball\VPinSPA
C:\VirtualPinball\VPinSPA\DmdDevice.dll
C:\VirtualPinball\VPinSPA\DmdDevice.ini

As you can see, I also put another copy of DmdDevice.dll (x86) and the DmdDevice.ini from DMD-Extensions into the VPinSPA folder. Also, I have the respective altcolor file into the VPinMAME folder.

Additionally, to the steps that you've said, I observed that I'd have to reinstall VPinMAME x86 and x64 again because they lost something, perhaps their respective keys in the registry, that made DMD-Extensions lost it color function for the PAC files in the Game-Which-Must-Not-Be-Named.

Anyway, I'll try your method to improve my installation to optimize it at maximum because I'm detecting some unnecessary redundancies in mine. Thank you!

Hope this helps for anyone suffering the same symptoms.

**Comment by KrakenByteKraken** [comment]
After a little bit of researching, I finally went following your steps and did it in that way because for a better optimization, you only will have one copy of DmdDevice.dll and DmdDevice.ini in your system.

For the same reason, I also stayed my "altcolor" file in the folder where all the other are:

- C:\VirtualPinball\VPinMAME\altcolor\spagb_100\spagb_100.cRZ

I also found that the "Bass.dll" can be updated by overwriting it with the newest version from VPinMAME.

And one more thing: When edit the key registry, remember that it's mandatory to **open a command prompt (CMD) as administrator**. And I must say that after done this step, I had must restart one of my PCs but in the other PC this wasn't necessary... (Mysterious mystery of the Window's misery... Ha, ha, ha, ha... I was kidding!).

And that's all, folks!
