### ISSUE TITLE
VR-GL v635

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#225]
First of all, thanks again for your continued support for the VR-GL, I just ran over 200 tables in VR and am happy to say that v635 is my best experience yet. I am running 64bit so I cannot comment on Pup Packs :)

I did however find a few minor issues;

- I continue to find reflection issues with some newer tables and the more I troubleshoot, the weirder it gets. Iron Man for example, testing on two systems (one single screen and the other my cab in VPX and VR) On my cab I cannot get ball or playfield reflections to show in VR or VPX but on my desktop (single screen) I can get ball reflections with all settings the same and several different table downloads. I also cannot see reflections with Teed Off VPX or VR set to dynamic reflections with table set to ball and playfield reflections on. Note, editing Teed Off's script to turn ball reflections on will not save, it always reverts back to off when I reload the table. This happens on many tables and started several builds ago.

- Once again I cannot load the new Machine Bride Of Pinbot in VR, works if I disable VR and launch with the VR-GL but not with VR enabled with 64bit

- Space Station VR Table throws an error, "VB Script S11.vbs version 3.65 or higher required"  (v3.36 is what we have) 

- Indiana Jones VPX did not show Playfield Reflections but a fresh download was able to fix that.

- Lastly, I dunno if this is a thing that is supposed to happen but every time I change the smallest thing like set a table for VR in the script or turn on ball reflections, the table file always changes size. Is that normal? 

This all sounds worse than it really is and I don't want to clutter up the issues section but felt there might be some good info in here :) I can mark this as closed after a bit, I just wanted to bring this to your attention as I don't hear anyone else noticing that their ball and playfield reflections are an issue with the few tables I have mentioned but the tables not saving changes and possibly the file changing size after a save might be a concern.

**Comment by toxieainc** [comment]
>Space Station VR Table throws an error, "VB Script S11.vbs version 3.65 or higher required" (v3.36 is what we have)

This is a table typo. I would guess that this should mean 3.56 in the script.

**Comment by toxieainc** [comment]
>Lastly, I dunno if this is a thing that is supposed to happen but every time I change the smallest thing like set a table for VR in the script or turn on ball reflections, the table file always changes size. Is that normal?

It would be an error if when you save the table twice with the same VPX, the size would still change.

Otherwise it depends on the VPX version the table was initially saved with. Cause newer VPX versions either can remove some duplicates, will remove some by now unused old stuff, OR will also add some new things that must be saved now.

**Comment by studlygoorite** [comment]
> > Lastly, I dunno if this is a thing that is supposed to happen but every time I change the smallest thing like set a table for VR in the script or turn on ball reflections, the table file always changes size. Is that normal?
> 
> It would be an error if when you save the table twice with the same VPX, the size would still change.
> 
> Otherwise it depends on the VPX version the table was initially saved with. Cause newer VPX versions either can remove some duplicates, will remove some by now unused old stuff, OR will also add some new things that must be saved now.

Maybe that's my issue with all of these things :) testing all of these builds and sometimes saving. I just downloaded Teed Off again and made a change and it saved on my desktop build no problem. Is there any way I could have locked a script from being able to save a change or could that be caused by saving with different builds again? Thanks

**Comment by vbousquet** [comment]
@studlygoorite Thanks also for your continued patience with all these little bugs crippling around!

I had a bit of free time, so I went for some tests regarding the issue you identified:
- reflections have been very alpha code and the way they are implemented have evolved across the beta version. When 'old' table are opened (that is to say tables that have been saved with an older VPX version), VPX will detect it and adjust the table to the new format in order to have everything ok. Since you are making regular tests, you may have opened a table with a preliminary implementation, save the table (so now marked as a 10.8 table) and then reopened it in a newer version but then VPX did not detect it as an 'old' version and did not adjusted it. If you re-download the table and reopen it, it will adjust it to the current state of the code and (likely) it should work. That could explains the headache you had.
- when saving with a new version of VPX, it is normal that the file size changes. As toxie said, it would not be normal is saving twice from the same version would not produce the same size
- I have pushed a few fixes in v645 that should hopefully solve some of the problems. Machine Bride of the Pinbot is supposed to work in VR in v645

Can you tell us if things are better now ?

**Comment by studlygoorite** [comment]
> @studlygoorite Thanks also for your continued patience with all these little bugs crippling around!
> 
> I had a bit of free time, so I went for some tests regarding the issue you identified:
> 
> * reflections have been very alpha code and the way they are implemented have evolved across the beta version. When 'old' table are opened (that is to say tables that have been saved with an older VPX version), VPX will detect it and adjust the table to the new format in order to have everything ok. Since you are making regular tests, you may have opened a table with a preliminary implementation, save the table (so now marked as a 10.8 table) and then reopened it in a newer version but then VPX did not detect it as an 'old' version and did not adjusted it. If you re-download the table and reopen it, it will adjust it to the current state of the code and (likely) it should work. That could explains the headache you had.
> * when saving with a new version of VPX, it is normal that the file size changes. As toxie said, it would not be normal is saving twice from the same version would not produce the same size
> * I have pushed a few fixes in v645 that should hopefully solve some of the problems. Machine Bride of the Pinbot is supposed to work in VR in v645
> 
> Can you tell us if things are better now ?

Thank you, I just gave VR-GL v645 64bit a go (just swapped out the .exe) and I got Machine Bride Of Pinbot to load twice in 6 tries. I did not have any reflections but you're gunna like this, regarding my reflections issue, I just found that not all VPX 10.8 builds are created equal when it comes to reflections, with my setup anyway. When editing a VR table does it use the VPX.exe version? Because I took the VPX.exe from my other PC that was showing reflections and put in in my cab and then downloaded a fresh version of Machine BOP and bingo, the reflections showed up. Same with the new Dirty Harry that came out today for VPX, I did not have reflections in my cab but after using the VPX.exe from my other PC all is good. So it looks like there are some builds out there that prevent the reflections from occurring. 

Just tried the latest VPX v645 32bit and 64bit (non VR) with the Dirty Harry table and no reflections showed, put the older VPX.exe back in from my other PC and reflections work great. I could find out what version this is that works if you need. Any who, I am happy that I figured out my reflections issue. Actually, if needed, I can run through as many builds as you want looking to see what builds show the reflections on these few tables with issues and what ones don't.....unless it's just me having this issue :)

**Comment by vbousquet** [comment]
Yes reflections used to be "stable" (luck would be a more appropriate word here :) ) and somehow I broke this stability but it is difficult to spot why since I can not reproduce this problem (they always work on my system) and the code is not easy to debug.

One thing I thought that could be tried is to start a table (that you have freshly downloaded, never edited with 10.8) with latest VPX (649+) and if it does not have reflections, press F11 multiple times to check 2 things:
- at some point it should display a screen labeled "Reflection probe" => could you take a screenshot and post it here (to check what is prepared for reflections) ?
- after using F11 a bunch of time, you will get back to the normal play => does the reflections are still missing or not (since I suspect a problem os render state defaults or stability) ?

**Comment by studlygoorite** [comment]
> Yes reflections used to be "stable" (luck would be a more appropriate word here :) ) and somehow I broke this stability but it is difficult to spot why since I can not reproduce this problem (they always work on my system) and the code is not easy to debug.
> 
> One thing I thought that could be tried is to start a table (that you have freshly downloaded, never edited with 10.8) with latest VPX (649+) and if it does not have reflections, press F11 multiple times to check 2 things:
> 
> * at some point it should display a screen labeled "Reflection probe" => could you take a screenshot and post it here (to check what is prepared for reflections) ?
> * after using F11 a bunch of time, you will get back to the normal play => does the reflections are still missing or not (since I suspect a problem os render state defaults or stability) ?

Ok tested a fresh download of the Dirty Harry table with VPX v649 and no reflections. Ran F11 through and reflections did not appear

![Screenshot (152)](https://user-images.githubusercontent.com/87738258/208720140-884caf89-00f4-42c9-bbe6-735b5a81536d.png)

**Comment by studlygoorite** [comment]
Just an update to this, I just tried VPX v672 32bit with a fresh download of the new Dirty Harry and still did not have playfield reflections, I popped in the latest 10.7.3 VPX 32bit and reflections show. Note, 10.7.3 is awesome, it fixed a minor stutter issue I had on all tables using all 10.8 builds and the reflections issue I was having with most 10.8 builds.

**Comment by studlygoorite** [comment]
Closing this issue and starting a new one with regards to just the reflections issue to keep it more organized.
