### ISSUE TITLE
Nudge strenght bug

### ISSUE THREAD

**Issue by zack06007** [vpinball/vpinball#249]
**Describe the bug**

When we nudge on 10.8 the screen don't move (nudge effect). I Try on 10.7.3 it's ok but no functiunning on 10.8.
The option is same Visual Nudge Strenght (0.0200) in vidéo option.

The nudge also is correct it's just the ''screen effect''

Thx for the ''nudgers'' 😁
zack06007

https://user-images.githubusercontent.com/87738258/210151860-ee2a1596-997b-44d5-95cd-e978a43b4c80.PNG

**Comment by Chickenzilla** [comment]
Yup.  It used to update some variables here https://github.com/vpinball/vpinball/blob/10.7.3/pin/player.cpp#L4429 and here https://github.com/vpinball/vpinball/blob/10.7.3/pin/player.cpp#L4609 but no longer does.  I think the devs may be aware because https://github.com/vpinball/vpinball/commit/4fe1d01a3418d7359567d06cc5863676bc8fc507 reverted the mainline changes for the 10.7.3 release.  Perhaps they just haven't gotten back to it yet.
