### ISSUE TITLE
BAM headtracking-Menu does not open.

### ISSUE THREAD

**Issue by mobutu16** [vpinball/vpinball#264]
Although BAM headtracking is working right now is not possible to configure the Axis, you need to do this configuration into BAM menú, the BAM Key to open is on the Bam.cfg file where BAMtracker.exe is.

If we cannot open BAM on play, it will be impossible to configure X, Y and Z axis.

System creates a BAMViewSettings.xml in Visual Pinball directory, try change some Scales, nothing happens

Need a call to open this BAM menu

**Expected behavior**
Open Menu to adjust x,y,z  #axis

**Versions**
 - VPX: 10.8.0 beta rev 716
 - Windows 10 Pro
 - GPU Nvidia 1660

**Comment by vbousquet** [comment]
Hi! I have relabelled this as a feature enhancement since I don't think this has ever been possible in any VPVR/VPX build. The current workaround should be to setup everything in FP then use VPX. We may eventually have a look for it but since, as far as I know, this is a closed source plugin without public API, this is unlikely to happen in the near future.

**Comment by mobutu16** [comment]
Setup with FO are work fine, works fine with 10.6 gl version.

https://youtube.com/watch?v=ZYJzlrSyUUg&feature=share

At description you have all the links to Vpx gl version.

only we need to export the same Bam option

**Comment by Gigalula** [comment]
Rafal Jancki released beta version and here is the file on this site that modified VPVR with a menu while playing in BAM headtraking with Kinect v2

https://sourceforge.net/u/ravarcade/vpvr/ci/607dabf6202e790aa7ef0980315430f5098bff93/#diff-11

here is the latest version from Rafal web site:

https://www.ravarcade.pl/beta/VPinballX_GL.zip

This last run 10.7 and if you use any VR table (10.6 or 10.7) it's running fine with menu ajustable as far as you don't use tables made with higher version of VPX even if some may work.

Thanks to all of you guys that could continue the work of Rafal prouve of concept because clearly this last seem too busy to follow 10.8 GL

BTW my setup he made and without the menu it's not possible to play tables

**Comment by mobutu16** [comment]
Agree @Gigalula , really needed to be implemented in 10.8.0., thats the reason to open this issue.
Hoping with your extensed explanation can solve asap.

**Comment by Gigalula** [comment]
We can call it a (BUG) because it’s not displaying correctly to be playable and a (FEATURE) need to be add to resize. 😉

**Comment by MikedaSpike** [comment]
is this issue causing the following screen with BAM (Kinetcv2) and VPVR_GL 10.8.726: 
![post-126997-0-34005700-1674576517](https://user-images.githubusercontent.com/48748234/214587750-489733a8-ac19-483c-bbdc-5e96565424d5.png)

Just wanted to create a new issue for this and see this one. Was not able to resize it

**Comment by Lecelte31** [comment]
@MikedaSpike , yes I believe this is the same issue.  I am having the same problem and cannot resize the table without the BAM menu. 
![20230124_223142](https://user-images.githubusercontent.com/123430625/214652418-b39ff452-2869-407f-afa0-7d761c6c67a6.jpg)

**Comment by MikedaSpike** [comment]
@vbousquet ,  isn't the issue that the table doesn't show correctly (shrinked)? I think thats a 'bug'

**Comment by ravarcade** [comment]
Hi,
I'll look into it next week or two.

**Comment by Lecelte31** [comment]
> Hi, I'll look into it next week or two.

You're the best, I love BAM headtracking in VPX. Thank you for looking into it whenever you have time, and no rush. I realize you all do this in your spare time :)

**Comment by vbousquet** [comment]
That's really great! I think it will play really nicely with the true anaglyph we have now.
I have started to look at your tutorials and starting to build a Wiimote headtracking device (just bought the right IR LED, waiting for delivery). Thanks!

**Comment by MikedaSpike** [comment]
@ravarcade , Gravy pointed us to a video that FP must run in portrait mode for correct working of BAM.
When setting VPX to portrait mode, it shows much better, but the Table is rotated 270 degrees.
![image](https://user-images.githubusercontent.com/48748234/220058895-125b7058-f9be-453c-8ffb-4d306085cba9.png)
But head  tracking is working, only need to set the table correct

**Comment by Gigalula** [comment]
BAM tiny menu is back in10.80 Build 807 via F11 key if you want to test... Ensure to load  each table once from VPinballX_GL.exe  and set via BAM menu "before" any attemp from external front end. Otherwise BAM menu won't be available from F11.

Thanks to all involved in VP and KUDO to Rafal Jancki to bring back this useful BAM menu.

**Comment by mobutu16** [comment]
Many very thanks, I'll give it a try band let u know. for sure will be ok.

**Comment by mobutu16** [comment]
During this time I wanted to see how the versions evolved and until the Beta 808 version, the menu with F11 appear but the image is very enlarged and it was impossible to reduce with the menu parameters. As of version 882 it already looks better but the menu with F11 has disappeared, it only shows the fps. Something has changed that the menu is no longer shown, in 808 and earlier it appears.

**Comment by mobutu16** [comment]
https://user-images.githubusercontent.com/391970/229374009-5e2ff3d0-694a-487c-8907-b65aa9064199.MOV

**Comment by Gigalula** [comment]
Last time info received from VBousquet:

copy past:
In game menu is indeed changing. So far, what is being done for keyboard shortcut is:

F11 => simply toggle FPS
ESC / Q => Show splash menu (Resume / Live Editor / Legacy Debugger / Quit)
Q long press => Quit
So no big change regarding how it used to behave.
Everything more advanced (BAM menu, video/audio settings, table inspection, renderer inspection, live editing,...) are moved to the live editor to allow to add more advanced stuff with live feedback, without bloating the UI for everyone

**Comment by MikedaSpike** [comment]
`Everything more advanced (BAM menu, video/audio settings, table inspection, renderer inspection, live editing,...) are moved to the live editor to allow to add more advanced stuff with live feedback, without bloating the UI for everyone`
I really like the love editor, but don't see anything for BAM. Is that still in progress?

**Comment by mobutu16** [comment]
Same here, no BAM options apper in live editor, Q simply quit.

**Comment by Gigalula** [comment]
I didn’t find out too 🤔

**Comment by vbousquet** [comment]
Latest version (1028+) has a direct access to the BAM settings from the main menu, with fullscreen feedback. Therefore, I will close the issue for now
