### ISSUE TITLE
VPX 10.8 1010 Results in VR with GL 64 Testing. Some may be by design or expected due to current development state some like 6 and 7 seem to definitely be bugs

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#417]
**Describe the bug**
I understand that now the settings for VPX no longer are stored in the registry and stored in an .ini file called VPinballX.ini now.  What i'm not sure on is if the settings were supposed to automatically copy over or not.  I'll assume they are and post my findings. 

1. All of my keys were back to their defaults.  That includes every key used like for flippers, magna save, extra ball buy in, Pinmame keys etc. 
2. My analog plunger lost all of its settings.  For example Axis, gain, deadzone 
3. My Analog accelerometer board lost all of the settings. X-Max Y-Max and % gain for each
4.  In the VR settings I lost the settings there including MSAA, SuperSampling, Post processing, and sharpen settings. 
5. My ball rendering settings along with ball image and decal are gone. 
6. The VR table recenter settings are lost after every game now.  I can center the table and raise and lower it but if I close out VP the settings are no longer saved so I have to redo this for every table I play even for tables I already played. 
7. Some video settings crash VPXGL when starting the table.  For example, post processing SMAA crashed VPX on all tables I tried. 
8. In keys nudge and DOF, I can't configure which keyboard or joystick button to use on my dual contact leaf switches. Ha... that one is a feature request :) 

**Versions**
 - VPX: [e.g.10.8 1010 64 GL
 - Windows version 11
 - Nvidia 3090
 - Valve Index 

Hope that this report  is helpful!  And thanks for all the work you guys put in to this hobby!

**Comment by vbousquet** [comment]
This is a nice and clear bug report! So, these were actually bugs and should be fixed in v1013.
Note that it lead me to change the location of the ini file. It will be in your %AppData%/VpinballX folder
If you could have a try and tell if it is working good for you (initialize from your old settings, except a few VR one that needs to be redefined, correctly save,...), that would be very kind

Note that SMAA is the last postprocess not working for OpenGL that needs to be ported. So it is not supposed to work for the time being

**Comment by gear323** [comment]
I started out by deleting the VPinballX.ini in my c:\VP directory to start out.    I then upgraded to the latest version 10.8.0 1017 and verified that indeed it no longer creates a new file there but instead it did create a file in %AppData%/VpinballX

Started the application and right away noticed when selecting "File" the history of my recent tables were back.  Before that was missing as well. 

I then checked all my buttons and ball decals and video settings etc, comparing them to screenshots I have from older versions and it looks like everything is there.  Started and played a few games and didn't notice anything not working.   

I also verified that now the VR table height and the VR table centering is stored when closing the tables or when restarting VPX GL

Looks like you resolved all of the issues there that I had mentioned above at least on my machine!

Just a thought, one issue we have is that the height and distance of tables is not always the same.   So even if we have a stationary VR pinball cab we need to adjust the height and distance of tables when switching between them.   A good example is theatre of magic, Jurassic park data east and black knight 2000.    Anyway, not sure how the best approach would be but maybe some day the table height and distance could somehow be auto detected by the lockdown bar height / location. 


Anyway,  Great work and thanks again!

**Comment by gear323** [comment]
One other thing,  Now that the settings have been imported from my registry, the Quality SMAA setting is selected again and it does not crash VPX.  Not sure if it is actually working though.  Anyway figured i'd mention that incase it is useful info at all.  Attached is my VR settings currently. 

![image](https://user-images.githubusercontent.com/108252542/235311100-deed3a56-91d0-45c6-b3bc-80a29f943813.png)

**Comment by vbousquet** [comment]
Thanks for the feedback, everything seems good then and I will close the issue.

Regarding the VR table height, one solution allowed by this version is to have a few .ini files with different height and when running, specify on the command line '-ini xxx.ini' xxx.ini being the settings with the height you want. With a frontend, this could be manageable but still very user friendly.

Quality SMAA is not working for OpenGL. It will not crash (now) but you should really not select it since it will eat performance, and actually downgrade image quality. All the others AA option are now fully working, so I would suggest to select the one of them.
