### ISSUE TITLE
Environment Emissions Settings 1138 - Legacy Editor!

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#484]
**Describe the bug**
In build 1138, within the interactive editor, the environment emissions setting does not make any visible changes.  Also, when leaving the interactive editor, the EE setting is not saved.

**To Reproduce**
Seems to happen every time.  Easily reproduced.

**Versions & Settings**
 - VPX: 1138
 - Windows version 11
 - GPU nVidia 3050

**Comment by vbousquet** [comment]
Just tested and it worked as intended.

Perhaps you adjusted on the wrong tab of the table ? You have the live table (the one you see) and the edited table (the one in the editor). You only see what is adjusted on the live table, and if you want to preserve the change you made to the live table, you need to press the little floppy disk near the change property for it to be saved to the edited table.

I will close for now since it seems to behave as expected

**Comment by Drybonz** [comment]
Sorry, I should have been more clear.  This is happening in the legacy editor that you reach through "tables>Interactive edit table".

**Comment by Drybonz** [comment]
Thanak you!
