### ISSUE TITLE
Default PF Reflection Strength Setting

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#485]
**Is your feature request related to a problem? Please describe.**
Playfield reflection strength must be set per table.

**Describe the solution you'd like**
Under "reflections" in "video/graphics options", would like to see a setting for "global pf reflection strength", which could be overrode with the current per table setting in the table editor.

**Comment by Drybonz** [comment]
This would also work well as a default LUT.

**Comment by Drybonz** [comment]
Spherical ball render settings is another one that would really benefit from a global setting in the video/graphics options with an override in the table settings.  I guess what I am getting at is more settings could benefit from a global setting so they don't have to be set on hundreds of tables.

**Comment by wiesshund** [comment]
Default LUT may not work, at least on all tables, i know on my tables it wont because it will change as soon as table inits, same with most of JP's.

Could be useful on those table that have not LUT period though.

Have you tried manipulating any of these via POV?

Like 
`    <customsettings>
        <SSAA>-1</SSAA>
        <postprocAA>-1</postprocAA>
        <ingameAO>-1</ingameAO>
        <ScSpReflect>-1</ScSpReflect>
        <FPSLimiter>-1</FPSLimiter>
        <OverwriteDetailsLevel>0</OverwriteDetailsLevel>
        <DetailsLevel>10</DetailsLevel>
		<ReflectionStrength>2.5</ReflectionStrength>
        <BallReflection>-1</BallReflection>
        <BallTrail>1</BallTrail>
        <BallTrailStrength>0.19607843</BallTrailStrength>
		<ReflectionOfPlayfield>0</ReflectionOfPlayfield>
		<DefaultBulbIntensityScale>1.6</DefaultBulbIntensityScale>
        <OverwriteNightDay>1</OverwriteNightDay>
        <NightDayLevel>32</NightDayLevel>
        <GameplayDifficulty>20</GameplayDifficulty>
        <PhysicsSet>0</PhysicsSet>
        <IncludeFlipperPhysics>0</IncludeFlipperPhysics>
        <SoundVolume>100</SoundVolume>
        <SoundVMusicVolumeolume>100</SoundVMusicVolumeolume>
    </customsettings>`

**Comment by vbousquet** [comment]
All properties that are considered as settings can now be defined per table using the 10.8's per table ini feature.
The properties you are mentioning here are really part of the table design and I don't think this makes sense to move them appart of the table. For example the spherical map of the ball entirely depends on the ball map. The LUT depends on the provided LUT textures and the script. The playfield reflections depends on if the author baked the table or not and how he managed holes (alpha or cutouts),...

I will close the issue for now since I can't see any way to implement the feature without making things complicated, not backward compatible. For your purpose, I think the way to go is to mod the table to your liking.
