### ISSUE TITLE
Fatal Error D3DERR_INVALIDCALL

### ISSUE THREAD

**Issue by M1L0S-R5** [vpinball/vpinball#488]
Last version of 10.8 which is working for me was 775 (file VPinballX-10.8.0-775-639a05c-Release-win-x64.zip). All later releases, inclusive latest Beta, always throw Fatal Error D3DERR_INVALIDCALL like this - https://ibb.co/C9YpLyb and program crashes

It happens with all tables and with both 32 and 64bit versions of Visual Pinball.

Tested with VPinballX-10.8.0-1138-fff5f9d-Release-win-x86, VPinballX-10.8.0-1138-fff5f9d-Release-win-x64, VPinballX-10.8.0-980-aedf6dc-Release-win-x64 - all crash

VPinballX-10.8.0-775-639a05c-Release-win-x64 - all works

**Expected behavior**
Table should open normally

**Screenshots**
[https://imgbb.com/](url)

**Crash dump**
Crash dump is ~2GB, 533MB zipped so I cannot be uploaded :(
[VPinballX_d3d9.log](https://github.com/vpinball/vpinball/files/11522459/VPinballX_d3d9.log)

**Versions & Settings**
 - VPX: Latest Beta 

 - Windows 11 64Bit
 - NVidia GeForce 3060 on Lenovo Ideapad Gaming 3 Laptop 
 - 
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11522468/VPinballX.zip)

**Comment by vbousquet** [comment]
As far as I can tell from the log, it looks like you are using DXVK. Is it right ?
If so, this is normal that you encounter problems since DXVK is not supported by VPX.

Beside, with the latest change, VPX already support OpenGL (latest version) beside DX9. So, I don't think DXVK would give benefits other the DX9 or OpenGL version. Does it ?

I will close the issue for now. Will reopen if it is something else

**Comment by M1L0S-R5** [comment]
Yes, this was it - many thanks!

DXVK is leftover from who knows when when I tried to troubleshoot some performance issues.
