### ISSUE TITLE
Drop Target not collidable when setting the collidable property to true

### ISSUE THREAD

**Issue by rothbauerw** [vpinball/vpinball#493]
In the latest version of VPX 10.8 build 1138, the collidable property for drop targets is not working when setting the value to true.  It works when setting it to false.

This can be seen on the latest release of Big Shot 1.3.1 https://vpuniverse.com/files/file/8492-big-shot-gottlieb-1974/

Knock down any target.  After the ball drains and the targets reset, that target will no longer drop on hit.  This is because the drop target object is not being properly set to collidable by VPX when the collidable property is set to true.  Note: there is also a wall object that is collidable slightly offset behind the drop target.  This wall will is properly set to collidable by VPX, which is what the ball is hitting instead of the drop target object.

 - VPX: 10.8 build 1138

**Comment by studlygoorite** [comment]
Just an FYI, found this issue with Genie also.

**Comment by vbousquet** [comment]
I did not find any changes on this part. Did this used to work on 10.7 or before ?

**Comment by rothbauerw** [comment]
Yes, this work on 10.7 & 10.6.

**Comment by rothbauerw** [comment]
This appear to be a 10.8 issue only.  Tested the latest 10.7.4 beta revision 404 and it works there.  I went back as far as revision 877 for 10.8 and it's broken there as well.  Tried going back further but the builds have expired.

**Comment by vbousquet** [comment]
This one took me a while to understand. The problem is in fact simple: when a drop target is hitten, it drops, when it is dropped, it can no more be hitten. Everything is coded like this, but before 10.8, the behavior was that a hidden target would never drop, therefore even after a first hit, it would receive additional hit events since it never dropped. I think this used to be a bug of previous versions since the physics behavior should not be linked to the render choice. Anyway, I will mimic the old buggy behavior for the sake of backward compability

**Comment by rothbauerw** [comment]
Tested in build 1189 and this still is not fixed.  Your description above didn't quite make sense to me.  In the tables referenced, the drop targets are not being dropped.  The physical targets are invisible and only the primitive targets drop.  The drop targets are only made non-collidable using the collidable property (droptarget1.collidable = false).  When trying to make them collidable again, it fails (droptarget1.collidable = true -> fails).

**Comment by rothbauerw** [comment]
Do you need me to create a new issue or can this one be re-opened?  I don't see an option for me to re-open.

**Comment by vbousquet** [comment]
Just have a look and I can confirm this is fixed. You need to test with a more recent build (the first one with the fix is 1222).

In VPX a drop target is collidable if and only if it is not dropped. That was the bug since the table is using drop targets but is expecting them to never dropped (which is the legacy behavior for hidden drop target). In 10.8, I started to fix this since I think this is not a correct behavior and have the physics behavior do not depend on the rendering (be it the visibility or the frame rate or the number of time a part is rendered). This solves a few bugs here and there but creates this backward compatibility problem. Anyway, for the time being, I reverted to the legacy behavior for drop targets. I will have a look later to fix this in a backward compatible way.

Regarding the table, I think the correct way would be either to use drop target and use there IsDropped property (and not the Collidable one, or at least use the both), or simply do not use drop targets and use normal hit target instead since you don't care about the dropped state.

**Comment by rothbauerw** [comment]
Confirmed fixed.
