### ISSUE TITLE
ffmpeg table video recording doesn't work with OpenGL

### ISSUE THREAD

**Issue by stojy** [vpinball/vpinball#524]
**Describe the bug**
The ffmpeg table video recording doesn't work with the OpenGL variant.  The video capture doesn't error, but the capture is entirely black.

Using the same VPX version and screen setup, the recording works correctly with the non-OGL variant.

Discussed here in VPF.. https://www.vpforums.org/index.php?showtopic=51455&p=519770.  And acknowledged as a 'low priority bug' to be fixed in the future.

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1189-a038732-Release-win-x64
 - Windows version: 10

**Comment by vbousquet** [comment]
This looks to me like a bad screengrab options for ffmpeg.
I saw also that Mike Da Spike did propose some setup [here](https://www.vpforums.org/index.php?showtopic=51455&p=520016) Did you have a try ?

Since I think the problem is the ffmpeg capture string of PinballY, I will close for now, please comment if you think this needs some action on VPX.

**Comment by stojy** [comment]
I don't have enough experience with the fffmpeg options to know if they're invalid for OGL.

But after updating fffmpeg to the latest version and also grabbing the latest 10.8 pipeline build the problem appears to have disappeared.  Which suggests the fffmpeg options used by PinballY may be fine after all.

Happy to have the issue closed.
