### ISSUE TITLE
GL - black textures

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#611]
Look like there are some rendering issues on this table. Only on GL 10.8, used latest build 1302

windows x64 and also visible on standalone macOS

Guns N Roses (Data East 1994).vpx (versins77)
https://vpuniverse.com/files/file/14967-guns-n-roses-data-east-1994

![image](https://github.com/vpinball/vpinball/assets/161305/7ba56028-1a60-4def-9de2-85ca85cd3a68)

**Comment by vbousquet** [comment]
I had a look and the table file seems to have been hacked somehow: materials contains invalid value (15 for glossiness and edges). This has to be fixed on the table file (simply edit the material and set those values to the 0..1 range), not VPX.

I will close for now since there does not seem to be anything to be done on the VPX side

**Comment by francisdb** [comment]
Thanks, might try to contact the author regarding those unexpected values.
