### ISSUE TITLE
Can't load PROC msgbox when launching Cactus Canyon Continued

### ISSUE THREAD

**Issue by CarnyPriest** [vpinball/vpinball#619]
**Describe the bug**
VPPlayer throws VBScript msgbox "Can't load PROC" on launching Cactus Canyon Continued (doesn' matter which table version). Clicking Ok causes table to proceed with normal launch. So, this is very minor.

**To Reproduce**
10.7.4 beta
Traced to change in script "controller.vbs" between release 408 and 410.

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPinballX-10.7.4-410-08587fa-Release-win-x86 w/P-ROC_Offline_Installer-v3.4 and current CCC game code from my repo - no change in game code since Apr 2022
 - Win10 Home 22H2
 -
 
**Additional context**

**Comment by CarnyPriest** [comment]
Hi, I'm just re-iterating that this is with the 10.7.2 fork. I'm not currently testing 10.8.

**Comment by thoznek** [comment]
I can confirm that the same problem is also present with the currently latest 10.8 beta release (both 32-bit and 64-bit). 
While the issue is indeed not the worst and the table runs after clicking 'OK', it is still annoying because when using a frontend (like PinballY), one must click the button in the popup window before the game can start.

**Comment by CarnyPriest** [comment]
The issue appears to be resolved with 10.8.0 beta 5 Thanks.
