### ISSUE TITLE
Cabinet not active after launching 10.8 beta 4 64bit GL

### ISSUE THREAD

**Issue by millertv79** [vpinball/vpinball#626]
I can’t do anything one the table loads. No buttons work. 

**To Reproduce**
1. Go to Popper
2. Launch a VR table 
3. Try to start game
4. No buttons on cab work nor would pushing keyboard buttons 

**Expected behavior**
To be able to use the buttons on my cab. Previously builds also have the same issue for me. Only one that work is rev 603 

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: 10.8.0 -1314-0f002da 64bit
 - Windows 11 Home 
 - GPU GeForce RTX 3050 8GB 
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 I’m on mobile and can’t right now 
**Additional context**

**Comment by vbousquet** [comment]
Your likely having a setting issue (we moved to a ini file setting sround the time it stopped working for you). Please check your setting and redefine your keyboards input if this is it, and tell us if it is ok now

**Comment by millertv79** [comment]
> 

Thanks for your reply! The only ini file I see in the VP folder is for open composite and there’s only one option on it. As far as I can see all my keyboard settings are the same. 

I’m having a new issue this morning where it won’t even load a table anymore. It will hour glass then kick me back out to oculus app. I’m gonna revert to my stable 603 build. Thanks for your work!

**Comment by millertv79** [comment]
i dont seem to have that directory 
![Screenshot 2023-07-11 080434](https://github.com/vpinball/vpinball/assets/25448173/22effde0-33a8-4b20-8462-e7ac3329944c)

**Comment by passionforpins** [comment]
make sure to unhide hidden folder. go to View, Show, Hidden Items

**Comment by gjenning** [comment]
I have this same issue.  When I load a vr table it is like vpx looses focus.  I have to click on the preview vr window to get focus and everything works fine from there.

**Comment by gjenning** [comment]
So after playing around with vpx_gl some more and vr I have discovered what the issue seems to be.  So when I connect my oculus headset, I put the headset on, use the oculus desktop to view my desktop, I then put down my oculus controller and use my wireless keyboard and trackpad to control the mouse in the desktop.  I load up VPX_GL, open up a table, and once the table is loaded in the GUI, I use the trackpad to click on the play button.  The table is then launched in the VR headset but is not active.  I have to do a <alt><tab> to give focus to vpx and the table runs just fine.  

I have found out that if instead of using the trackpad to click on the play button and pickup the oculus controller, which gets the mouse focus, and I click on the play button, the vr table is launched and the table is in focus and everything works as expected.  

Using the trackpad was not a issue in earlier releases of 10.8 VPX_GL.  This is also causing me a issue when trying to launch VR Tables through a frontend like pinpu popper vr.

**Comment by millertv79** [comment]
> Your likely having a setting issue (we moved to a ini file setting sround the time it stopped working for you). Please check your setting and redefine your keyboards input if this is it, and tell us if it is ok now

Hey Vincent - just wanted to chime in that I still can’t get focus with the newest beta 5 either. I use joy2key on my alp because I can’t direct map the d pad and need that for my button setup. So I don’t have them directly mapped in vpx. Any tips to have it retain focus like in the earlier build 603?

**Comment by gjenning** [comment]
@vbousquet The issue I was having with the cab loosing focus has gone away with version 1450.  @millertv79 I would test to see if you are still having issue but I am thinking that this issue has been resolved and can probably be closed.

**Comment by millertv79** [comment]
> @vbousquet The issue I was having with the cab loosing focus has gone away with version 1450. @millertv79 I would test to see if you are still having issue but I am thinking that this issue has been resolved and can probably be closed.

thanks for that! I'm on 1448 and it seems to be fine as well, I ditched my vpx focus app and have no problems starting a table
