### ISSUE TITLE
GL Build: Anaglyph separation is off-axis

### ISSUE THREAD

**Issue by Billiam** [vpinball/vpinball#700]
**Describe the bug**

When using anaglyph 3d modes in the GL 10.8 build, the anaglyph separation is off axis, in a radial pattern, instead of horizontal-only.

This does not affect the DX build.

It's most noticeable in the front apron usually, because it can be less busy and high contrast:

![Front apron when using green/magenta anaglyph mode](https://github.com/vpinball/vpinball/assets/242008/2fb97fb5-2bec-441b-8147-d5e3d5cd738b)

On the left side, the magenta separation is down and to the right. On the right side, the magenta separation is up and to the right.

I've heard this is a known bug, but I couldn't find any issues discussing it.

**To Reproduce**

1. Use 10.8 GL build
2. Enable anaglyph 3d mode
3. Observe 3d separation is not horizontal

**Expected behavior**

All anaglyph separation is horizontal-only (or vertical only in cab mode), as it does for the DX builds.

**Versions & Settings**
 - VPX: 10.8.0 Beta (Revision 1314 (0f002da), 32 bit)
 - Win 10 19045.3324

**Comment by bhamscott** [comment]
This is a big one - thanks for reporting it... Apparently its the reason for significant eye strain discomfort when the "eye separation" setting approaches anything about 50 (small child IPD). Adult IPD average is 70mm

**Comment by vbousquet** [comment]
I have just pushed a redesign of the anaglyph projection based. I moved away from the parallax (used before 10.8) and toe-in (used in 10.8 until my latest commit, which leads to the distortion you describe) to the more correct offaxis parallax projection which is supposed to be the right one (as far as I understand and read, this is what is used for VR as well).

I also changed the way the '0 depth' is placed:
- for cabinet mode (known as 'window' mode) it is placed at the 'window' position since the window is the screen and everything is supposed to be inside it
- for desktop mode, it is placed at the nearest element, leading to the table to be inside the screen, limiting the eye strain

I did not touch (yet) to the anaglyph composition.

It looks good (way better at least) to me. Feedback welcomed !

**Comment by Billiam** [comment]
@vbousquet Thank you!

Is the zero point adjustable at all? In desktop mode, I prefer to have 0 be somewhere around the flippers for greatest clarity, and some 'pop out',

For cabinet mode, it might depend on monitor placement (some popout may be desirable if they're mounted 'low', or none if they're mounted close to flush).

**Comment by vbousquet** [comment]
The 0 depth stereo point is not adjustable. This is on purpose since this would add up some complexity and work, and would also lead to some difficulties since if it opens the door for negative parallax stereo which is likely to be wrongor at least have artefacts.

For cabinet, I don't think this is a problem since there is the 'Window' mode that precisely defines where the 0 depth point (the window is the screen, you set its position with the Z top/bottom offset) and that's what is used for stereo.

For desktop, it's less obvious but I really prefer to avoid opening another can of worms...

**Comment by vbousquet** [comment]
To be more precise. I would like to avoid another obscure user setting that breaks everything with wrong value. But I think the default I have put in this first commit (nearest object) may not be the right one. Perhaps selecting the bats could be better as you propose. I may test this when I have the time

**Comment by Billiam** [comment]
> Perhaps selecting the bats could be better

I feel like that would be a better default if it can't be made configurable.

I think the other issue with 'closest object' is that the camera may be set up to cut the nearest object off (ex: by cutting off the apron), so the "starting" value is already into the screen a ways.

**Comment by vbousquet** [comment]
I did some testing and changed the 0 depth line for desktop mode. I placed it near the flipper bats zone (the best I could get was at 2/3 down the playfield to balance the depth budget between negative and positive parallax without creating eye strain). I agree that it gives really better and more stable depth sensation.

**Comment by Billiam** [comment]
The new zero depth is indeed better, though in all the tables I tested, the 2/3rds mark isn't especially near the flippers, so those still have a lot of separation, unfortunately.

Example with high separation for illustration, zero point is a bit above the slingshots: ![zpd](https://github.com/vpinball/vpinball/assets/242008/8af00d4f-2933-47f5-bbc3-43c1f4cbf354)

Personally, I think that the ideal values (particularly in desktop mode) are going to be too dependent on the user needs, and the differences in tables themselves to have fixed ZPD position like this. I think it's a sensible default, but should be user editable.
