### ISSUE TITLE
Anaglyph calibrated colors not working as expected

### ISSUE THREAD

**Issue by Billiam** [vpinball/vpinball#777]
**Describe the bug**

The calibrated colors do not appear to be applying in a expected way.

The default Green/Magenta colors are an OK match but in testing outside of VPX, there are better color pairs that are appropriately brighter and darker for this pair of glasses.

When creating a calibration profile to match these, there is no difference in the anaglyph output, compared to the default profile.

I'm guessing this is a part of the gamma/fitting settings, but it also seems to be shifting hue color especially on the right in this case

**To Reproduce**

1. Edit VirtualPinballX.ini, replacing anaglyph settings for one profile:
    ```ini
    anaglyph7leftred = 0.000000
    anaglyph7leftgreen = 1.000000
    anaglyph7leftblue = 0.090000
    anaglyph7rightred = 0.659562
    anaglyph7rightgreen = 0.000000
    anaglyph7rightblue = 0.120438
    anaglyph7fittedleftred = 0.000793
    anaglyph7fittedleftgreen = 0.989404
    anaglyph7fittedrightred = 0.752304
    anaglyph7fittedrightgreen = 0.018262
    anaglyph7fittedgamma = 0.683961
    ```
3. Launch VPX
4. Start table
5. Open live UI editor
6. Select edited profile
7. Verify calibration colors examples appear as expected (almost pure green, magenta)
8. Change profile to default Green/Magenta
9. Verify calibration colors have changed radically
10. Verify that anaglyph color has not changed at all

**Expected behavior**

Differenc colors are used for anaglyph based on calibration

**Screenshots**

Default Green/Magenta:
![VPinballX_GL64_oGlDRYoi9r](https://github.com/vpinball/vpinball/assets/242008/6d312769-ea0d-46b9-bad8-fb1d44ddc9cd)

Calibrated colors:
![VPinballX_GL64_coJ5i7Ekqh](https://github.com/vpinball/vpinball/assets/242008/f7e7c4e2-f1f1-43ca-bec2-f7791fb93a81)

The luminance filter was selected here accidentally, instead of none, but I see the same output, and image diff, with the filter set to 'luminance' or 'none' for both of these profiles.

Image diff: 
![difference](https://github.com/vpinball/vpinball/assets/242008/70fa921e-6acd-471c-8908-606aa21faa29)

**Versions & Settings**
 - VPX: GL 10.8.0 Beta (Revision 1436 (6125cdd), 64bit)

**Comment by vbousquet** [comment]
Having the same result with the none filter is what is expected: the 'None' filter is a basic full color filter (the calibration only allows to identify which colors, but is not used for tweaking them).

I did test with the Luminance and DynDest (which use the calibration not only to identify glasses but also to fit the filter to them) and I do get a difference between these settings:
![image](https://github.com/vpinball/vpinball/assets/2796036/224d064e-59a5-46a0-816b-b9235a502036)

I'm not 100% sure about the fact that the difference is not so big while the UI shows a very different color, but it looks ok to me since the UI shows a normalized inverse filter while the algorithm uses the direct filter. I don't think there is any bug here, so I will close

**Comment by Billiam** [comment]
> the calibration only allows to identify which colors, but is not used for tweaking them

So with the filter set to 'none', the calibration doesn't affect the actual separation colors by design?

**Comment by vbousquet** [comment]
@Billiam I have added stereo to the docs to make things more clear (https://github.com/vpinball/vpinball/tree/master/docs)
