### ISSUE TITLE
SSR seems to differ in brightness GL <-> DX

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#815]
**Describe the bug**
GLs SSR seems to be way darker than DXs one. I couldn't find a reason in the code for this yet.

**Versions & Settings**
 - VPX: rev 1479
 - dynamic AO off, PostAA off, sharpening off, just SSR

**Comment by vbousquet** [comment]
The commit improves the ting but is not a real fix. The fact is that the SSR implementation rely on a somehwat hacky since normal reconstruction is not stable => this should be improved more but should wait for 10.8.1 since this part of the shader will change a lot while moving to more modern API.
I will close this issue since this is okish and this part needs a full rewrite to be really ok targeting 10.8.1 or later

**Comment by toxieainc** [comment]
@vbousquet I just commited some old experiment for better normal computations, maybe its useful later-on.
I didn't commit it so far as the tradeoff performance vs quality was not really worth it (i.e. on lower end hardware).

**Comment by vbousquet** [comment]
Will have a look. The results are not bad now (that's why I closed the issue) but they are not really good either. I was thinking of using coordinate reocnstruction and dx/dy derivatives to build the cross product. I think I used that on another project and it did worked well. The tradeoff is between texture fetches versus shader complexity.
