### ISSUE TITLE
Insert lights work in DX but not in GL

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#914]
**Describe the bug**
On the GL version of 10.8 the inserts for `Capersville (Bally 1966)` don't light up

https://vpuniverse.com/files/file/10814-capersville-bally-1966/

VPinballX_GL-10.8.0-1579-224c661-Release-win-x64
VPinballX-10.8.0-1579-224c661-Release-win-x64

### DX

https://github.com/vpinball/vpinball/assets/161305/11b4bbed-7c0f-4588-b94f-2b8899beb261

### GL

https://github.com/vpinball/vpinball/assets/161305/7b59661d-8da2-453b-8e22-7ca96865e70f

**Comment by Scottacus64** [comment]
So the problem here is that the "inserts" object with "Render2" as it's image is blocking the lights from showing up.  If I turn the visibility of "inserts" to off then the lights show through the playfield and flasher above it.  This is on an M1 mac running standalone.
![Screenshot 2023-10-13 at 11 46 12 AM](https://github.com/vpinball/vpinball/assets/70824106/70d105ba-2aa7-4413-8530-0ce00c9da722)

**Comment by vbousquet** [comment]
There was bug in VPX (shader state which was not persisted correctly while rendering reflection probe). It's now fixed (in main, Jason will have to rebase to get the fix in standalone)
