### ISSUE TITLE
Change the menu section of "Disable B2S" setting

### ISSUE THREAD

**Issue by KrakenByteKraken** [vpinball/vpinball#925]
I allways forget that this setting is in the other section because I think that it's a graphical option but it's a keys option, so I allways search it in the wrong place.

I think that this setting could be more confortable living into the graphics options menu instead in its actual keys options menu.

So, could be possible to change the "Disable B2S" seting from "Configure Keys, Knudge and DOF..." to "Video/Graphics Options..." section?

Thanks in advance and regards!

**Comment by TurboHenk** [comment]
I don't agree, I use "Disable B2S" only for my plunger. 

So for me it's not a graphical option at all but a key option. So in my opinion the current location is fine.

**Comment by KrakenByteKraken** [comment]
_B2S_ means _Backglass 2nd Screen_ like is said in [the GitHub **b2s-backglass** project page](https://github.com/vpinball/b2s-backglass) and because that I thought it's a graphical setting feature.

But maybe I'm wrong, perhaps it's well emplaced in the place where always had must to be and I'm only a confused human and all was a crazy idea.

Anyway, thanks for enjoy all this amazing developent: VPX is awesome!

**Comment by TurboHenk** [comment]
> _B2S_ means _Backglass 2nd Screen_ like is said in [the GitHub **b2s-backglass** project page](https://github.com/vpinball/b2s-backglass) and because that I thought it's a graphical setting feature.
> 
> But maybe I'm wrong, perhaps it's well emplaced in the place where always had must to be and I'm only a confused human and all was a crazy idea.
> 
> Anyway, thanks for enjoy all this amazing developent: VPX is awesome!

True, I understand your way of thinking about it. 

But there's something else to think about: there are currently two graphical settings menu's in VPX 10.8: 2D/non-VR and for VR. VR has it's own video settings and can also use B2S. I have some "custom modded" VR tables that need B2S. But the disable B2S setting could/should be at one place. It cannot be in both: VR settings and Video/Graphics Options.

And some users (including me) use B2S mostly for the plunger(that's what I mainly think about when I read "disable B2S"=disable my DOF support). 

For those two reasons I think that a more general placement for "disable B2S" (as it is now, at "Configure Keys, Knudge and DOF") is better then putting it in the 2D table options because it always disables DOF support. 

End conclusion; I got a solution: call the menu "Configure Keys, Knudge and DOF." -> "Configure Keys, Knudge**, DOF and B2S**." Then it's 100% clear and logical in all cases.

**Comment by KrakenByteKraken** [comment]
Thanks for your detailed explanation. It's true that when disabling B2S then its plugins doesn't work any more, so there will be no Backglass and no DOF. And this could be the rason to put the B2S in the section where DOF lives.

I never thought that, in some cases, DOF could affect to plunger settings but I don't know how works every pincab in the world.

Because, in my case, I only use DOF to turn on some LEDs and it lives apart from my plunger settings witch are based in a standalone KL25Z (without the expansion boards) Pinscape controller.

So I can turn off B2S (turning off DOF and loosing all its beautiful illumination effects) but I can still use my plunger to play with it.

At the end of the day, I feel B2S more like a graphical enchacement than a keys adjustment. But, perhapps is smarter to put it in another dedicated section or rename it as you said. Lets to the developers think about this, they can do it... and make it better again and again.
